### ISSUE TITLE
Assign LuaRef to itself failed

### ISSUE THREAD

**Issue by rysson** [vinniefalco/LuaBridge#100]
When assign to LuaRef from itself, for example:

``` C++
void fun(LuaRef a)
{
  if(a.isTable())
    a = a["key"];
} 
```

I've got an error:  "attempt to index a number value"

I guess, that in LuaRef::operator=() first step is luaL_unref and there is no table to access than.

When I change my code to:

``` C++
LuaRef b = a["key"];
a = b;
```

everything is working.

**Comment by dmitry-t** [comment]
Fixed by #165.
