### ISSUE TITLE
How to call lua function in C++?

### ISSUE THREAD

**Issue by eliteYang** [vinniefalco/LuaBridge#101]
platform:win7
lua:5.3

lua file
```lua
test = {}

test.Init = function(kernel, self, arg)
	io.write("Hello Lua Init!\n");
end

test.AfterInit = function(kernel, self, arg)
	io.write("Hello Lua AfterInit!\n");
end
```

C++ file
```c++
luabridge::LuaRef compent = luabridge::getGlobal(luaState, "test");
luabridge::LuaRef func = compent.getGlobal(luaState, "Init");
func(NFScriptIdent(kernel, self, arg);
```
I got an assert, 

I tried to use
```c++
luabridge::LuaRef func = luabridge::getGlobal(luaState, "test.Init");
func(NFScriptIdent(kernel, self, arg);
```

it's still assert.

so I'm confused, plz help me, thanks

**Comment by JoshuaBehrens** [comment]
Well at first you are always missing a ) in the last line of your c++ code. What kind of assert do you get? This is most important question here. This will give us the point where the problem is, then we can easily resolve why this problem is there.

Interesting is: what NFScriptIdent, too? A function (then the return type is important) or a macro (then the macro definition is important)?
To detect what getGlobal returned we can at first have a look at its type. So check at least LuaRef::type() or LuaRef::isFunction() and LuaRef::isNil().

**Comment by eliteYang** [comment]
I resolved this problem, I pass a int64_t to lua function, stack is broken.
so when luabridge will support lua 5.3 and int64_t?

thanks @JoshuaBehrens

**Comment by JoshuaBehrens** [comment]
AFAIK is LuaBridge not #1 on @vinniefalco priority list and I must admit I didn't knew about 5.3. 5.3 was released 6 weeks ago so it will take some time.

But as the feature list is not that huge you can make the compatibility by yourself. If you read a bit into LuaBridge source it will be easy for you to extend the functionality. If it is just support for 64bit integer think twice wether you need it (isn't 32bit enough?) and you can return two 32bit integer and later pass them as arguments to convert them in c++ back to 64bit, but you cannot use 64bit integer. AFAIK is lua 5.2 capable of representing 53bit integers using doubles so if you do not need the whole 64bit range but more than 32bit that might be useful.

**Comment by vinniefalco** [comment]
5.3? There's a new Lua?

**Comment by eliteYang** [comment]
thanks all, I try to use a struct that include two 32bit.

**Comment by eliteYang** [comment]
and I try to read luabridge's source code, try to support lua_integer.
today I add LuaRef.push<lua_integer>, there still has some stack error, I stll work on it, gl for me.

**Comment by JoshuaBehrens** [comment]
@vinniefalco Yes there is new lua. Mainly utf8 and 64bit support.

@eliteYang gl

**Comment by eliteYang** [comment]
@vinniefalco yeah, new lua 5.3 is released. http://www.lua.org

**Comment by eliteYang** [comment]
@vinniefalco Can you update luaBridge to support int64_t? thanks

**Comment by vinniefalco** [comment]
Unfortunately I'm not in the right context to do that and I have other tasks that I'm working on, so it will be difficult. Are there any volunteers?

**Comment by eliteYang** [comment]
@vinniefalco OK, I got it, I try to update it later

**Comment by JoshuaBehrens** [comment]
I only have interest in the utf8 part. But as @vinniefalco I am working and do not think that I have time for that.

**Comment by eliteYang** [comment]
@JoshuaBehrens  I have interest in int64_t part, so we can do it together
