### ISSUE TITLE
Assertion failed when binding a function containing "char*" type argument

### ISSUE THREAD

**Issue by coderev** [vinniefalco/LuaBridge#102]
The new LuaBridge will raise an assertion failure when binding a function which has "char\* " type arguments.
The test code can reproduce this problem as following:

``` cplusplus
class A 
{
protected:
    char*   newname;
public:
    A(char* _name)
    {
        newname = _name;
    }

    std::string getName()
    {
        return this->name;
    }

    void printName()
    {
        printf("Hello, my name is %s!\n", this->newname);
    }
};
```

And the registration of functions is:

``` cplusplus
    luabridge::getGlobalNamespace(L)
        .beginClass<A>("A")
                .addConstructor<void(*) (char *)>()
                .addFunction("getName", &A::getName)
                .addFunction("printName", &A::printName)
        .endClass();
```

The lua content is as bellow:

``` lua
local b = A('moo')
b:printName()
```

Then when starting the host program, lua will promopt a message about "assertion failure"

![assertion failure](https://cloud.githubusercontent.com/assets/11421154/6593399/5f57a2c6-c813-11e4-99fc-305845905b0e.png)
Please does anyone have encountered such a problem?
Thanks very much.

**Comment by coderev** [comment]
Forget to describe my test env:
     **lua 5.3 - the latest from official site**
     **luabridge - the latest**

small modification to luabridge to pass the compilation:

(Stack.h, line 458)

```cplusplus
  static inline void push (lua_State* L, std::string const& str)
  {
    lua_pushstring (L, str.c_str());
    // lua_pushstring (L, str.c_str(), str.size());
  }
```

**Comment by coderev** [comment]
Btw, even change the Stack.h (line 458) to following, still cannot avoid the assertion failure

```
  static inline void push (lua_State* L, std::string const& str)
  {
	lua_pushlstring(L, str.c_str(), str.size());
    // lua_pushstring (L, str.c_str(), str.size());
  }
```

**Comment by m1k0s** [comment]
Surely the problem is that you are not taking a copy of the lua string...

Keeping just a char* is not enough as lua will move this around from under
your feet (or even gc it).

On Wed, Mar 11, 2015 at 9:52 AM, coderev <notifications@github.com> wrote:

> Btw, even change the Stack.h (line 458) to following, still cannot avoid
> the assertion failure
>
>   static inline void push (lua_State* L, std::string const& str)
>   {
>     lua_pushlstring(L, str.c_str(), str.size());
>     // lua_pushstring (L, str.c_str(), str.size());
>   }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vinniefalco/LuaBridge/issues/102#issuecomment-78233304>
> .
>



-- 

*steliaros*.com

**Comment by coderev** [comment]
Thanks for your kindly reply, but I'm not sure if we are talking about the same thing?
I mean the assertion failure will happen when I try to bind a function which has "char* " as arguments.
From my understanding, I followed a normal procedure to do the binding, the char pointer is from the source of host program which the arguments type should not be taken care by **LuaBridge**, and there is also no need to take a copy of it in host source?
Correct me if I misunderstand, or would you please show me a case on how to solve it by taking a copy of the string?
Thanks.

**Comment by coderev** [comment]
@m1k0s :smiley:Are you mentioning the change of the "push" function but not this topic?
>
Surely the problem is that you are not taking a copy of the lua string...
>
Keeping just a char* is not enough as lua will move this around from under
your feet (or even gc it).

**Comment by m1k0s** [comment]
I should have read more carefully ;)

I assumed the abort was due to accessing the string at runtime (which _is_
a problem in your example and may or may not cause a crash) and missed the
assert in your screenshot...

Because you are using char* (rather than const char*) you are picking up
the non-specialised Stack implementation for T* which assumes T is a
userdata rather than a string...

The correct use in this case is to change to:

   A(const char* _name)

and:

.addConstructor<void(*) (const char *)>()

(in fact you only technically to make this change to addContructor but
that would be hacky.).

I still maintain that storing a lua owned pointer like this natively
is wrong though and jsut asking for trouble - just change it to a
std::string or at least copy the lua string in you A class (strdup or
something).


On Wed, Mar 11, 2015 at 12:57 PM, coderev <notifications@github.com> wrote:

> @m1k0s <https://github.com/m1k0s> [image: :smiley:]Are you mentioning the
> change of the "push" function but not this topic?
>
> Surely the problem is that you are not taking a copy of the lua string...
>
> Keeping just a char* is not enough as lua will move this around from under
> your feet (or even gc it).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vinniefalco/LuaBridge/issues/102#issuecomment-78257727>
> .
>



-- 

*steliaros*.com

**Comment by coderev** [comment]
@m1k0s 
Thanks, yes it works when add "const" before char*, but then how can I modify a memory block if a pointer cannot be passed to lua?
Like this
```C
void UpdateMem(byte* _mem)
{
    ...
    // manipulate the memory
}
```
How can I register such a function to Lua?

**Comment by m1k0s** [comment]
What are you trying to do exactly?

luabridge aside, lua _strings_ should be treated as immutable from the
native side:

http://www.lua.org/pil/27.2.html

if you want a buffer that you have direct control over then I'd use
userdata (which is what luabridge ultimately helps manage).

On Thu, Mar 12, 2015 at 3:57 AM, coderev <notifications@github.com> wrote:

> @m1k0s <https://github.com/m1k0s>
> Thanks, yes it works when add "const" before char*, but then how can I
> modify a memory block if a pointer cannot be passed to lua?
> Like this
>
> void UpdateMem(byte* _mem)
> {
>     ...
>     // manipulate the memory
> }
>
> How can I register such a function to Lua?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vinniefalco/LuaBridge/issues/102#issuecomment-78419979>
> .
>



-- 

*steliaros*.com

**Comment by dmitry-t** [comment]
Answered.
