### ISSUE TITLE
Several errors on LuaHelpers.h when including LuaBridge.h and compiling

### ISSUE THREAD

**Issue by ale-carra** [vinniefalco/LuaBridge#105]
I included LuaBridge.h in a .cpp file and tried to compile it, but I get the following errors:

In file included from LuaBridge.h:54:0,
                 from main.cpp:1:
detail/LuaHelpers.h:33:26: error: ‘luabridge::lua_absindex’ declared as an ‘inline’ variable
 inline int lua_absindex (lua_State\* L, int idx)
                          ^
detail/LuaHelpers.h:33:26: error: ‘lua_State’ was not declared in this scope
detail/LuaHelpers.h:33:37: error: ‘L’ was not declared in this scope
 inline int lua_absindex (lua_State\* L, int idx)
                                     ^
detail/LuaHelpers.h:33:40: error: expected primary-expression before ‘int’
 inline int lua_absindex (lua_State\* L, int idx)
                                        ^
detail/LuaHelpers.h:33:47: error: expression list treated as compound expression in initializer [-fpermissive]
 inline int lua_absindex (lua_State\* L, int idx)
                                               ^
detail/LuaHelpers.h:34:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
detail/LuaHelpers.h:41:26: error: variable or field ‘lua_rawgetp’ declared void
 inline void lua_rawgetp (lua_State\* L, int idx, void const\* p)
                          ^
detail/LuaHelpers.h:41:26: error: ‘lua_State’ was not declared in this scope
detail/LuaHelpers.h:41:37: error: ‘L’ was not declared in this scope
 inline void lua_rawgetp (lua_State\* L, int idx, void const\* p)
                                     ^
detail/LuaHelpers.h:41:40: error: expected primary-expression before ‘int’
 inline void lua_rawgetp (lua_State\* L, int idx, void const\* p)
                                        ^
detail/LuaHelpers.h:41:49: error: expected primary-expression before ‘void’
 inline void lua_rawgetp (lua_State\* L, int idx, void const\* p)
                                                 ^
detail/LuaHelpers.h:48:26: error: variable or field ‘lua_rawsetp’ declared void
 inline void lua_rawsetp (lua_State\* L, int idx, void const\* p)
                          ^
detail/LuaHelpers.h:48:26: error: ‘lua_State’ was not declared in this scope
detail/LuaHelpers.h:48:37: error: ‘L’ was not declared in this scope
 inline void lua_rawsetp (lua_State\* L, int idx, void const\* p)
                                     ^
detail/LuaHelpers.h:48:40: error: expected primary-expression before ‘int’
 inline void lua_rawsetp (lua_State\* L, int idx, void const\* p)
                                        ^
detail/LuaHelpers.h:48:49: error: expected primary-expression before ‘void’
 inline void lua_rawsetp (lua_State\* L, int idx, void const\* p)
                                                 ^
detail/LuaHelpers.h:61:25: error: ‘luabridge::lua_compare’ declared as an ‘inline’ variable
 inline int lua_compare (lua_State\* L, int idx1, int idx2, int op)
                         ^
detail/LuaHelpers.h:61:25: error: ‘lua_State’ was not declared in this scope
detail/LuaHelpers.h:61:36: error: ‘L’ was not declared in this scope
 inline int lua_compare (lua_State\* L, int idx1, int idx2, int op)
                                    ^
detail/LuaHelpers.h:61:39: error: expected primary-expression before ‘int’
 inline int lua_compare (lua_State\* L, int idx1, int idx2, int op)
                                       ^
detail/LuaHelpers.h:61:49: error: expected primary-expression before ‘int’
 inline int lua_compare (lua_State\* L, int idx1, int idx2, int op)
                                                 ^
detail/LuaHelpers.h:61:59: error: expected primary-expression before ‘int’
 inline int lua_compare (lua_State\* L, int idx1, int idx2, int op)
                                                           ^
detail/LuaHelpers.h:61:65: error: expression list treated as compound expression in initializer [-fpermissive]
 inline int lua_compare (lua_State\* L, int idx1, int idx2, int op)
                                                                 ^
detail/LuaHelpers.h:62:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {

**Comment by KostasPelelis** [comment]
Its probably too late, but this might happen when you are trying to compile LuaBridge with Lua that is not customized to be build with C++ supoort. All you need to do though, is add the following to the `LuaHelpers.h` file.

`#include <lua/src/lua.hpp>`
