### ISSUE TITLE
calling class member failed

### ISSUE THREAD

**Issue by norbertbarbosa** [vinniefalco/LuaBridge#108]
tested with last luaBridge master, with Lua 502, compiled with vs2010 win32.

For the following code:
```C++
# include <lua.hpp>
# include <LuaBridge/LuaBridge.h>

struct A {
	std::string str;
	const char* getCustom(const char* val) {
		return val;
	}
	A(): str("foo") {}
};

//#define SCRIPT "return a.str"
#define SCRIPT "return a.custom(\"foo\")"
int main()
{
	lua_State* L = luaL_newstate ();
	luaL_openlibs (L);

	luabridge::getGlobalNamespace(L)
		.beginClass<A> ("A")
			.addData("str", &A::str, false)
			.addFunction("custom", &A::getCustom)
		.endClass();

	A* a = new A;
	luabridge::push(L, a);
	lua_setglobal (L, "a");

	int error = luaL_loadstring(L, SCRIPT);
	if(!error) error = lua_pcall(L, 0, 1, 0);
	
	delete a;

	if (error) {
		printf("ERROR: %s\n", lua_tostring(L, -1));
	} else if(lua_isnoneornil(L, 0)) { 
		printf("FAILED: nil\n");
	} else if(lua_isstring(L, 0)) { 
		printf("SUCCEED: %s\n", lua_tostring(L, -1));
	} else {
		printf("FAILED: undefined\n");
	}
	lua_close (L);
	return 0;
}
```
I expect to have result ```SUCCEED: foo```
but have ```ERROR: [string "return a.custom("foo")"]:1: bad argument #1 to 'custom' (A expected, got string)```

Note that if I try with ```SCRIPT = return a.custom(a, "foo")```, it works.
It is a bug, or a bad usage?

**Comment by JoshuaBehrens** [comment]
Your script is syntactically(is this a word?) wrong. It is the other way round in Lua as in C++. In C++ you use :: for static namespace or sub-class calls and . for member functions of an instance. In Lua you use . for static namespace or sub-class calls and : for member functions of an instance.

**Comment by norbertbarbosa** [comment]
thanks a lot for the clarification :)
I should start to read the lua syntax, before trying to embed it on my app...

Thanks and sorry
