### ISSUE TITLE
Documentation link broken (alternative provided here)

### ISSUE THREAD

**Issue by Darelbi** [vinniefalco/LuaBridge#109]
The documentation and demos linked in main page (LuaBridge/README) are broken, I found on the web this one:

http://a8u-tutorial-sources.googlecode.com/git-history/311fd6c18b5548db7d52f1e59eaf45c1a37b5533/Game/External/LuaBridge-2.0/Manual.html#s2.6

but I don't know if it is updated enough against LuaBridge to cover all details or changed stuff. Hope you put online the official manual soon . cheers ^^

Great library, much better than luabind.

**Comment by Darelbi** [comment]
The broken link is this one:
http://vinniefalco.github.com/LuaBridge

**Comment by Darelbi** [comment]
Is this project still active? it is pretty awesome.

**Comment by dmitry-t** [comment]
Fixed.
