### ISSUE TITLE
If you map class and it's constructor throws an exception, the object’s destructor is run (RAII issues).

### ISSUE THREAD

**Issue by CatsCanSmile** [vinniefalco/LuaBridge#114]
Hi, example:

``` c++
struct Test
{
  Test()
  {
    std::cout << "Test()"<< std::endl;
    throw std::runtime_error("boom!");
  }
  ~Test()
  {
    std::cout << "~Test()"<< std::endl;
  }
};

int main()
{
 lua_State*  l_state = luaL_newstate();
  try
  {
    luaL_openlibs( l_state);
    luabridge::getGlobalNamespace( l_state)
      .beginClass< Test >( "Test")
      .addConstructor <void (*) ()> ()
      .endClass();
    luaL_dostring( l_state, "tmp = Test()"); 
  }
  catch(const std::exception& e)
  {
    std::cout << "ex:" << e.what() << std::endl;
  }
  catch(...)
  {
    std::cout << "..." << std::endl;
  }
  lua_close( l_state);
  return 0;
}
```

Output:

``` console
Test()
ex:boom!
~Test()
```

According to C++ standard object Test is not fully constructed, so object’s destructor should not run.

Possible solution:
Add flag in class UserdataValue. Set flag after actual mapped class construction in ctorPlacementProxy. Call object's destructor in ~UserdataValue only if flag is set.

**Comment by ihavnoid** [comment]
I am not sure if throwing exceptions like that can be eventually safe.  By throwing exceptions we simply skipped any possible cleanup routine internal to lua.

One suggestion is to have luabridge catch C++ exceptions and convert them back to lua_error or luaL_error so that lua can handle the rest of the cleanup.  In fact I was looking for a way for C++ code to throw exceptions to have lua gracefully clean it up.

**Comment by dmitry-t** [comment]
> I am not sure if throwing exceptions like that can be eventually safe. By throwing exceptions we simply skipped any possible cleanup routine internal to lua.

A programmer cannot guarantee a constructor doesn't throw. There may external reasons e.g. lack of memory or disk space or network connectivity.

The worst thing here is that field destructors are called *twice*: first time after the constructor throws and second time after the destructor body.

So the solution is to set a flag telling the construction went okay, and checking it during garbage collection. The C++ standard guarantees that if a field constructor is successful, its destructor is  called once the parent class constructor throws.
I'm going to use the existing `m_p` pointer as a flag to save some memory though it makes the code i bit more complicated.
