### ISSUE TITLE
Setting a global variable to an already initialized variable.

### ISSUE THREAD

**Issue by Snorflake** [vinniefalco/LuaBridge#115]
Hey, so I was wanting to hook up this
```
getGlobalNamespace(L)
			.beginNamespace("CSGO")
				.beginClass<CEngine>("Engine")
					.addFunction("Cmd", &CEngine::ClientCmd)
				.endClass()
			.endNamespace();
```

I can only have one instance of the class (It points to a game class)

I have initialized the variable fine and I can call its functions fine in C++.
```
luabridge::getGlobalNamespace(L)
		.beginNamespace("CSGO")
			.addVariable("Engine", &g_pEngine, false)
		.endNamespace();
```
I'm trying to add an instance of it to the global namespace. I want to be able to call the function from CEngine in lua. (At this moment, I think it's best i mention g_pEngine is a CEngine*)

But when i try and do this

`CSGO.Engine:Cmd("clear;echo testing123")`

it throws me this error
` exec.lua:1: attempt to call a nil value (method 'Cmd')`

How can I fix this?

EDIT: Using lua 5.3

**Comment by EliasD** [comment]
This is not a Luabridge issue.
When you do this:
```cpp
     addVariable("Engine", &g_pEngine, false)
````
you are passing a pointer to a pointer. 
You should do this instead:
```cpp
    addVariable("Engine", g_pEngine, false)
````

**Comment by Snorflake** [comment]
That still didn't fix it.

**Comment by EliasD** [comment]
Can you post a complete minimal example which reproduces the error?
The error is probably somewhere in your code, not in LuaBridge.

This code works.

````cpp
#include <LuaBridge.h>

int main()
{
    using namespace luabridge;
    int* x = new int(5);
    lua_State* L = luaL_newstate();
    luaL_openlibs(L);
    getGlobalNamespace(L).
        beginNamespace("test")
             .addVariable("x", x)
        .endNamespace();
    luaL_dostring(L, "test.x=4"); // x = 4 after this line
}
````

**Comment by Syndwar** [comment]
Is CEngine::ClientCmd static? If so, than you don't need beginClass<CEngine>("Engine")

And just call CSGO.Engine.Cmd("clear;echo testing123")

**Comment by Snorflake** [comment]
No, CEngine::ClientCmd isn't static.

EliasD, the reason that works is because im trying to set a variable to a class, and call a function from that class.

**Comment by EliasD** [comment]
This works, so the problem is somewhere else.

````cpp
#include <iostream>

class Test {
public:
    void f()
    {
        std::cout << "This works" << std::endl;
    }
};

int main()
{
    using namespace luabridge;
    Test* x = new Test;
    lua_State* L = luaL_newstate();
    
    luaL_openlibs(L);
    getGlobalNamespace(L).
        beginNamespace("test")
        .beginClass<Test>("Test")
            .addFunction("f", &Test::f)
        .endClass()
        .addVariable("x", x)
        .endNamespace();
    luaL_dostring(L, "test.x:f()");
}
````

**Comment by Snorflake** [comment]
try doing it without a namespace, and making the variable read-only

**Comment by EliasD** [comment]
But you did it with namespaces in your original post...

Okay, I've found the source of the problem. 
You can't currently bind C++ variables to globals in Lua (you probably shoudn't, anyway)
The problem is that when you call addVariable, it tries to get "__propget" table which is created for namespace tables which LuaBridge creates. _G table doesn't have this table, so addVariable fails.
Try modifying _G table like it's done in  Namespace (char const* name, Namespace const* parent) constructor and see if you can bind variables this way
(Modifying _G like this is probably a bad idea, that's why you should use namespaces or maybe even not use globals at all!)

**Comment by Syndwar** [comment]
LuaBridge manual
1.1 - Design
Global variables (variables must be wrapped in a named scope)

**Comment by Snorflake** [comment]
That's probably it then. I found a reference on what i'm trying to implement https://github.com/MarkHC/LuaCSGO/ and started rewriting it with LuaBind. Now to switch BACK over to my LuaBridge project and re-create it!

I wont be using global variables :p
