### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by iamclint** [vinniefalco/LuaBridge#116]
error C2955: 'luabridge::CFunc::Call' : use of class template requires template argument list Namespace.h   1083

error C2976: 'luabridge::CFunc::Call' : too few template arguments Namespace.h  1083

vs2013 Express

.addFunction("PrintChat", GameFunctions::PrintChat)

static int GameFunctions::PrintChat(char *Format, ...);

**Comment by iamclint** [comment]
.addFunction("PrintChat", GameFunctions::PrintChat)

is where it fails

**Comment by Snorflake** [comment]
try `.addFunction("PrintChar", &GameFunctions::PrintChat)`

**Comment by dmitry-t** [comment]
Answered.
