### ISSUE TITLE
Is there some way to use operators?

### ISSUE THREAD

**Issue by Snorflake** [vinniefalco/LuaBridge#117]
Say i have a Vector class of floats (x, y ,z) and i have operators defined for Vector (+ - * /)
How can I declare them? In luabind it was like this
```
				.def(luabind::const_self + luabind::const_self)
				.def(luabind::const_self - luabind::const_self)
				.def(luabind::const_self * luabind::const_self)
				.def(luabind::const_self / luabind::const_self)
				.def(luabind::const_self * luabind::other<float>())
				.def(luabind::const_self / luabind::other<float>())
```

but i can't find any info on it for luabridge

**Comment by m1k0s** [comment]
.addFunction("__eq", &maths::Vec3f::operator==)

.addFunction("__unm", &maths::Vec3f::operator-)

.addFunction("__add", (maths::Vec3f (*)(const maths::Vec3f&, const maths::
Vec3f&))&::operator+)

.addFunction("__sub", (maths::Vec3f (*)(const maths::Vec3f&, const maths::
Vec3f&))&::operator-)

.addFunction("__mul", (maths::Vec3f (*)(const maths::Vec3f&, const maths::
Vec3f&))&::operator*)


But remember luabridge will not handle overloaded methods for you like
luabind does...

Mike

On 13 December 2015 at 16:23, Snorflake <notifications@github.com> wrote:

> Say i have a Vector class of floats (x, y ,z) and i have operators defined
> for them (+ - * /)
> How can I declare them? In luabind it was like this
>
>                 .def(luabind::const_self + luabind::const_self)
>                 .def(luabind::const_self - luabind::const_self)
>                 .def(luabind::const_self * luabind::const_self)
>                 .def(luabind::const_self / luabind::const_self)
>                 .def(luabind::const_self * luabind::other<float>())
>                 .def(luabind::const_self / luabind::other<float>())
>
> but i can't find any info on it for luabridge
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vinniefalco/LuaBridge/issues/117>.
>



-- 

*steliaros*.com

**Comment by Snorflake** [comment]
That's throwing me an error
`.addFunction("__add", (Vector(*)(const  Vector&, const Vector&))&::operator+)`

```
1>main.cpp(51): error C2039: '+' : is not a member of '`global namespace''
1>main.cpp(51): error C2065: '+' : undeclared identifier
```

**Comment by m1k0s** [comment]
Do you have a global operator+? In my case I have:

maths::Vec3f operator+(const maths::Vec3f& lhs, const maths::Vec3f& rhs);



On 13 December 2015 at 23:50, Snorflake <notifications@github.com> wrote:

> That's throwing me an error
> .addFunction("__add", (Vector(*)(const Vector&, const
> Vector&))&::operator+)
>
> 1>main.cpp(51): error C2039: '+' : is not a member of '`global namespace''
> 1>main.cpp(51): error C2065: '+' : undeclared identifier
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vinniefalco/LuaBridge/issues/117#issuecomment-164312204>
> .
>



-- 

*steliaros*.com

**Comment by Snorflake** [comment]
No i do not. I fixed it by making a subtraction function
```
	Vector sub(Vector& const v)
	{
		return (*this - v);
	}
```
and using that instead of the operator

**Comment by josh33901** [comment]
hi snorflake.
i was trying to implement this to
`.addFunction( "__vmul", static_cast<Vector( Vector::* )( const Vector & )const>( &Vector::operator* ) )`
turns out you can use a static cast to tell the compiler which one you want.
hope this helps
