### ISSUE TITLE
call the function with a parameter vector<string>

### ISSUE THREAD

**Issue by Faltul** [vinniefalco/LuaBridge#122]
How from Lua to call a C ++ function that has a parameter of type vector <string>

void TestFunction(const vector<string> s) {

}

**Comment by dmitry-t** [comment]
For now you add the specialization luabridge::Stack<std::vector<YourType>>, as described in [the manual, section 2.6](http://vinniefalco.github.io/LuaBridge/Manual.html#s2.6).

**Comment by dmitry-t** [comment]
Added specialization ` template <class T> std::vector <T>`.
