### ISSUE TITLE
The User Manual site may crash ?!

### ISSUE THREAD

**Issue by hu78h** [vinniefalco/LuaBridge#125]
Sorry to disturbed, but the user manual of LuaBridge http://vinniefalco.com/LuaBridge somehow doen't work. It said 'The Server dropped connection'. Is it any server problem? Or could you provide offline documentation please?

**Comment by m1k0s** [comment]
The manual is committed in the repo:

https://github.com/vinniefalco/LuaBridge/blob/master/Manual.html

Just save the raw version of this locally...

On 23 March 2016 at 03:14, hu78h <notifications@github.com> wrote:

> Sorry to disturbed, but the user manual of LuaBridge
> http://vinniefalco.com/LuaBridge somehow doen't work. It said 'The Server
> dropped connection'. Is it any server problem? Or could you provide offline
> documentation please?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vinniefalco/LuaBridge/issues/125>
>



-- 

*steliaros*.com

**Comment by hu78h** [comment]
Oh~Thanks a lot!
