### ISSUE TITLE
access enum value

### ISSUE THREAD

**Issue by cgloeckner** [vinniefalco/LuaBridge#127]
Hi, I registered my structs and classes to be usable from lua. But some of the structs contain enum values. What's the prefered way to register an enum using LuaBridge?

Minimal code example

``` c++
#include <lua5.2/lua.hpp>
#include <LuaBridge/LuaBridge.h>

enum class Foo {
    A,
    B,
    C
};

struct Data {
    Foo f;
};

int main() {
    // load script
    lua_State* lua = luaL_newstate();
    luaL_openlibs(lua);
    std::string code =
        "f = function(data)\n"
        "   print(data.f)\n"
        "end";
    luaL_dostring(lua, code.c_str());

    // register types
    luabridge::getGlobalNamespace(lua)
        .beginClass<Data>("Data")
            .addData("f", &Data::f)
        .endClass();

    // call script
    Data d;
    d.f = Foo::A;
    luabridge::getGlobal(lua, "f")(d);
}
```

Causes:
`./LuaBridge/detail/Userdata.h:375: static void *luabridge::UserdataValue<Foo>::place(lua_State *const) [T = Foo]: Assertion `(lua_type(L, (-1)) == 5)' failed.`

What I expect is some kind of int-converted output through print.

/EDIT: I just found a solution specializing the `Stack<>`

``` c++
/// Use as base for stack specializations to enable enum conversion
template <typename T>
struct EnumWrapper {
    static inline
    typename std::enable_if<std::is_enum<T>::value, void>::type
    push(lua_State* L, T value) {
        lua_pushnumber(L, static_cast<std::size_t>(value));
    }

    static inline
    typename std::enable_if<std::is_enum<T>::value, T>::type
    get(lua_State* L, int index) {
        return static_cast<T>(lua_tointeger(L, index));
    }
};
```

And finally register enums via

``` c++
template <>
struct luabridge::Stack<MyEnumType>
    : EnumWrapper<MyEnumType> {
};
```

**Comment by dmitry-t** [comment]
Answered by the author of the question :)

**Comment by ThisMeansYou** [comment]
Hi, thanks for sharing!

Can you please continue the explanation?
I implemented the struct in my binder class, what shall I do next? how do I register all of my enum constants?:
 
template <>
struct luabridge::Stack<MyEnumType>
    : EnumWrapper<MyEnumType> {
};

**Comment by ThisMeansYou** [comment]
What do I do if my enum is nested inside a class / struct? is it possible to reveal it to Lua this way?
