### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by elvismd** [vinniefalco/LuaBridge#129]
Im making an engine in c++ with lua for scripting, so i have a lot of entities, and those entities has components, one of the components that i have is of course a script component, but, everytime i want to call a different function from a lua file, i always have to call luaL_dofile, and if I do this more than 20 times, i mean, with 20 scripts, my engine gets REALLY slow like, 5 fps. Every script has a Init, FixedUpdate, Update and Shutdown function, so for every script, i call the Init function, for every script i call the update function, and so on... 
There's a solution for that? I really hope someone could help me

**Comment by Syndwar** [comment]
Create common_scripts.lua,
put each script into function,
load file it once when the game starts.

Load each script by it's function name from global scope using GetGlobal (or any other way you can call a function).

**Comment by dmitry-t** [comment]
Answered.
