### ISSUE TITLE
why not release 2.0

### ISSUE THREAD

**Issue by LinkerJL** [vinniefalco/LuaBridge#135]
I want to use this lib of version **2.0** in my project. But the latest release version is **1.0.2**.
Why not release 2.0? Are there still many bug need to fix?

**Comment by LinkerJL** [comment]
As far as I know, there are 3 bugs.

1. In `Source/LuaBridge/detail/Stack.h` line 460
`lua_pushstring (L, str.c_str(), str.size());` should be 
`lua_pushlstring (L, str.c_str(), str.size());`

1. In `Manual.html` line 669
`static int staticCFunc () { return 0; }` should be 
`static int staticCFunc (lua_State *L) { return 0; }`

1. In `Manual.html` line 704
`.addStaticProperty ("staticProperty", &amp;A::staticProperty)` should be
`.addStaticProperty ("staticProperty", &amp;A::getStaticProperty, &amp;A::setStaticProperty)`

**Comment by dmitry-t** [comment]
The first point has been fixed.
