### ISSUE TITLE
passing float array from Lua to C\C++ using LuaBridge

### ISSUE THREAD

**Issue by nitroxn** [vinniefalco/LuaBridge#136]
how to pass a float array from Lua when a C\C++ function is called. If it is possible to pass it by converting to lua table it should be acceptable

**Comment by m1k0s** [comment]
It will not be done for you automatically.

Have a method/function that takes a (luabridge::LuaRef value) as a parameter (check that value.isTable() is true and raise a lua error if not) then copy the values out using what you'd expect:

float* dst = ...;
for(int count = value.length(), i = 1; i <= count; ++i)
  *dst++ = value[i];

(remember that lua arrays start at 1)

To do the opposite have a method/function return a LuaRef that is populated from a float[]...

**Comment by dmitry-t** [comment]
LuaBridge now supports passing array as std::vector. Just include `<LuaBridge/Vector.h>`.
