### ISSUE TITLE
Expected '}' at end of input.

### ISSUE THREAD

**Issue by AeroSW** [vinniefalco/LuaBridge#141]
The issue is occurring in my project which I have included "LuaBridge.h".  I am sure you probably have all of the brackets closed, but the error disappears whenever I comment out the '#include "LuaBridge.h"'.  This points to it being the originator.

`
 #include <LuaBridge.h>
 
 class hello;
`
displays the error for me.  Those are the only 2 lines in my file.

This is with GCC 6.2

**Comment by DragonSmile** [comment]
> #include "lua.h"
> #include "lualib.h"
> #include "lauxlib.h"

These three header is required by `LuaBridge.h`,so you should add them before
> #include "lua.h"
> #include "lualib.h"
> #include "lauxlib.h"
> #include "LuaBridge.h"
