### ISSUE TITLE
error: unknown type name 'lua_State'

### ISSUE THREAD

**Issue by morteryler** [vinniefalco/LuaBridge#146]
I use clang and g++
`
In file included from main.cpp:2:
In file included from ./LuaBridge.h:54:
./detail/LuaHelpers.h:33:26: error: unknown type name 'lua_State'
inline int lua_absindex (lua_State* L, int idx)
                         ^
./detail/LuaHelpers.h:35:13: error: use of undeclared identifier 'LUA_REGISTRYINDEX'
  if (idx > LUA_REGISTRYINDEX && idx < 0)
            ^
./detail/LuaHelpers.h:41:26: error: unknown type name 'lua_State'
inline void lua_rawgetp (lua_State* L, int idx, void const* p)
                         ^
./detail/LuaHelpers.h:48:26: error: unknown type name 'lua_State'
inline void lua_rawsetp (lua_State* L, int idx, void const* p)
                         ^
./detail/LuaHelpers.h:61:25: error: unknown type name 'lua_State'
inline int lua_compare (lua_State* L, int idx1, int idx2, int op)
                        ^
./detail/LuaHelpers.h:82:24: error: unknown type name 'lua_State'
inline int get_length (lua_State* L, int idx)
                       ^
./detail/LuaHelpers.h:106:26: error: unknown type name 'lua_State'
inline void rawgetfield (lua_State* L, int index, char const* key)
`./detail/TypeList.h:160:12: error: unknown type name 'lua_State'
  ArgList (lua_State*)
           ^
./detail/TypeList.h:169:12: error: unknown type name 'lua_State'
  ArgList (lua_State* L)
           ^
In file included from main.cpp:2:
In file included from ./LuaBridge.h:60:
./detail/Stack.h:35:15: error: use of undeclared identifier 'lua_State'
struct Stack <lua_State*>
              ^
./detail/Stack.h:35:25: error: expected expression
struct Stack <lua_State*>
                        ^
./detail/Stack.h:48:15: error: use of undeclared identifier 'lua_CFunction'
struct Stack <lua_CFunction>
              ^
./detail/Stack.h:68:28: error: unknown type name 'lua_State'
  static inline void push (lua_State* L, int value)
                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by SirRamEsq** [comment]
I had a similar issue; I had incorrectly included LuaBridge.h first, then the Lua headers like so:
```

#include <LuaBridge.h>
extern "C" {
#include "lua5.2/lauxlib.h"
#include "lua5.2/lua.h"
#include "lua5.2/lualib.h"
}

```
LuaBridge should be included after the headers, however, like so:
```
extern "C" {
#include "lua5.2/lauxlib.h"
#include "lua5.2/lua.h"
#include "lua5.2/lualib.h"
}
#include <LuaBridge.h>
```

Post back if this resolves your issue.

**Comment by dmitry-t** [comment]
Answered.
