### ISSUE TITLE
Can't re-open class

### ISSUE THREAD

**Issue by DannyvanSwieten** [vinniefalco/LuaBridge#149]
The following asserts on the second `beginClass` call in `rawgetfield` when getting the `__const` field.       
Am I missing something? The reference convinced me this is valid use of the API.

```
luabridge::getGlobalNamespace(L).
        beginNamespace("Engine").
        beginClass<Entity>("Entity").
        endClass().
        beginClass<Entity>("Entity").
        endClass().
        endNamespace();
```

**Comment by DJLink** [comment]
You have beginClass with Entity twice, you need to wrap all functions into one begin/end I think

` beginClass<Entity>("Entity").
.addFunction("func_1", &MyClass::do_stuff1)
.addFunction("func_2", &MyClass::do_stuff2)
.addFunction("func_3", &MyClass::do_stuff3)
  endClass().`

**Comment by DannyvanSwieten** [comment]
Thanks for your response. That indeed works, but the reference manuals says the following:
![screen shot 2018-03-15 at 12 54 10](https://user-images.githubusercontent.com/3296444/37461836-11be6f90-2850-11e8-850a-1634d6af46d8.png)

**Comment by m1k0s** [comment]
https://github.com/vinniefalco/LuaBridge/issues/55

**Comment by DannyvanSwieten** [comment]
Thank you!

**Comment by dmitry-t** [comment]
Hey guys, who is responsible for the project now?  Vinnie, please respond.
