### ISSUE TITLE
Calling a function from Lua which takes a wide string as argurment make the program crash

### ISSUE THREAD

**Issue by TronFortyTwo** [vinniefalco/LuaBridge#152]
Tested on Debian GNU/Linux x86_64, using latest LuaBridge version and compiled with clang++ with -std=c++14.

Steps to reproduce:
- Create a class with a function which takes as an argurment a std::wstring.
```
class my_class{
public:
    void fun(const std::wstring& w_str);
};
```
- Expose the class to Lua, and expose the function too
```
...
luabridge::getGlobalNamespace(L)
    .beginClass<my_class>("my_class")
        .addFunction("fun", &my_class::fun)
    .endClass();
```
- Compile. No error/warning reported
- Call the function from Lua
```
-- my_script.lua
my_class:fun("test")
```
- Expected result:
The function is called successfully, or an error/warning is printed if this is not possible.

- Actual result: execution is terminated with this error
```
tato: ./LuaBridge/Source/LuaBridge/detail/Userdata.h:189: static luabridge::Userdata *luabridge::Userdata::getClass(lua_State *, int, const void *, bool): Assertion `lua_istable (L, -1)' failed.
Aborted
```

**Comment by dmitry-t** [comment]
The "fun" method is an object method so it requires something to operate on. The "my_class:fun()" notation means there should be a non-nik my_class table.
It is unclear from your code, where did you get the my_class object. The posted fragment in C++ would mean

    ((my_class*) 0)->fun()

Which is probably no what you want.

**Comment by TronFortyTwo** [comment]
Thanks for the answer. You're right, the code I posted was wrong, sorry. I post the complete code here:
```
/*
    LuaTest.cpp
*/
...
// class definition
class my_class{
public:
    // note: std::wstring, not std::string. The same code with std::string works
    void fun(const std::wstring& w_str);
};
...
void callLua()
{
    // new Lua state
    lua_State *L = luaL_newstate();
	
    // open Lua libraries
    luaL_openlibs(L);
	
     // open file
    if ( luaL_loadfile(L, "my_script.lua") )
    {
        // manage loading failure
        ...
    }

    // expose the class 
    luabridge::getGlobalNamespace(L)
        .beginClass<my_class>("my_class")
            .addFunction("fun", &my_class::fun)
        .endClass();

    // push a my_class object in the Lua stack
    my_class my_object; 
    luabridge::push(L, my_object);
    lua_setglobal(L, "my_object");

    // execute the script
    if ( luaL_dofile( L, "my_script.lua" ) != 0 ) 
    {
        ...
        // manage execution failure
    }
    // Close script
    lua_close(L);
}
...
```
and the Lua part
```
-- my_script.lua
my_object:fun("test wide string")
```

**Comment by dmitry-t** [comment]
What is the expected behavior?

**Comment by TronFortyTwo** [comment]
I do not know the internals of LuaBridge, but as I written in the first post the function should be called successfully (with an implicit conversion to wide string), or an error/warning is printed, but not cause the whole process (not only the Lua call) to terminate

**Comment by dmitry-t** [comment]
Oh, sorry. I see.

Such crashes is a usual behavior when you try to access a non-registered class (for debug builds the assert is triggered). In your scenario `std::wstring` is not registered as a class.

The simplest way to make your code with wstring working is to a add `Stack <>` specialization for std::wstring. E.g. (the string <-> wstring conversion here is just for example, probably not suitable for real applications):
```
namespace luabridge {

template <>
struct Stack <std::wstring>
{
  static void push (lua_State* L, std::wstring const& wstr)
  {
    std::string str(wstr.begin(), wstr.end());
    lua_pushlstring (L, str.c_str (), str.size());
  }

  static std::wstring get (lua_State* L, int index)
  {
    size_t len;
    const char *str = luaL_checklstring(L, index, &len);
    return std::wstring (str, str + len);
  }
};

template <>
struct Stack <std::wstring const&>
{
  static void push (lua_State* L, std::wstring const& wstr)
  {
    std::string str(wstr.begin(), wstr.end());
    lua_pushlstring (L, str.c_str (), str.size());
  }

  static std::wstring get (lua_State* L, int index)
  {
    size_t len;
    const char *str = luaL_checklstring(L, index, &len);
    return std::wstring (str, str + len);
  }
};

} // namespace luabridge
```

**Comment by TronFortyTwo** [comment]
I see, thanks.
As a developer who doesn't know LuaBridge internals thought is confusing and unexpected that the error cause a crash of the whole execution (not only of the Lua call) and that there is no explainatory error message. But I think this is a different issue related with the library design and implementation.
Keep up with the good work!
