### ISSUE TITLE
 E2247 'LuaRef::LuaRef(lua_State *,LuaRef::FromStack)' is not accessible

### ISSUE THREAD

**Issue by sdragonx** [vinniefalco/LuaBridge#155]
LuaRef.h:
    //--------------------------------------------------------------------------
    /**
        Call Lua code.

        These overloads allow Lua code to be called with up to 8 parameters.
        The return value is provided as a LuaRef (which may be LUA_REFNIL).
        If an error occurs, a LuaException is thrown.
    */
    /** @{ */
    LuaRef const operator() () const
    {
      push (m_L);
      LuaException::pcall (m_L, 0, 1);
      return LuaRef (m_L, FromStack ());
    }

**Comment by dmitry-t** [comment]
Could you please post the client code leading to the compiler error?
What is the MSVC version you are using?

**Comment by sdragonx** [comment]
g++ or c++builder

**Comment by dmitry-t** [comment]
OK, could yoy please post a minimal code example?

**Comment by dmitry-t** [comment]
The code should compile and run with this change: #193.

**Comment by dmitry-t** [comment]
Closing due to lack of information.
Please feel free to reopen the issue or create a new one.
