### ISSUE TITLE
Problem with Proxy Table class, assert(0) called

### ISSUE THREAD

**Issue by gem81** [vinniefalco/LuaBridge#161]
Lua
`t = { aa=1,bb=2, othert={1,2,3} }`
simple table with table inside
if i try to get internal table
```
	LuaRef t = getGlobal(L, "t");
	LuaRef othert = t["othert"];
```
it's call assert(0) in
```
    Proxy (Proxy const& other)
      : m_L (other.m_L)
      , m_tableRef (other.m_tableRef)
    {
      // If this assert goes off it means code is taking this path,
      // which is better avoided.
      //
      assert (0); // ???????????????????? !!

      lua_rawgeti (m_L, LUA_REGISTRYINDEX, other.m_keyRef);
      m_keyRef = luaL_ref (m_L, LUA_REGISTRYINDEX);
    }
```
for what reason its calling assert(0);????
sorry, if i dup topic(

**Comment by dmitry-t** [comment]
It's strange, the providing code works with MSVC 2017.
Which MSVC version do you use?
Is the provided code really enough to reproduce the issue?

```C++
TEST_F (IssueTests, Issue161)
{
  runLua ("t = { aa=1,bb=2, othert={1,2,3} }");

  luabridge::LuaRef t = luabridge::getGlobal (L, "t");
  luabridge::LuaRef othert = t ["othert"];
  ASSERT_TRUE (t ["othert"].isTable ());
}
```

**Comment by gem81** [comment]
2017
But i build with /clr option.
Platform windows 10.xxxx, vc141. .net 4.6.1

**Comment by gem81** [comment]
wooooow
Now it's all ok! i did't do nothing ((((( 
just rebooted the computer

**Comment by dmitry-t** [comment]
Just in case I tried to compile tests with /CLR option (additionally reset /RTC1 to default and set /MTd to /MDd to successfully build), and got no problem.
