### ISSUE TITLE
How to iterator luabridge::LuaRef within table?

### ISSUE THREAD

**Issue by hcaihao** [vinniefalco/LuaBridge#163]
```
	luabridge::LuaRef ori(g_pLua, luabridge::newTable(g_pLua));
	ori.append(1);
	ori.append(2);
	ori.append(3);
```

When I get ori, how to iterator it, help pls!

**Comment by dmitry-t** [comment]
There is `luabridge::Iterator` class, you can use it for iteration.

Also I am going to extend its interface to enable STL-like iteration (begin/end/range based for).

**Comment by hcaihao** [comment]
I access ori like this:

```
for (int i = 1; i <= ori.length(); i++)
{
 int v = ori[i];
}
```

Is it correct?

**Comment by dmitry-t** [comment]
This way you only can iterate over sequences.
To iterate over any table:
```C++
    for (luabridge::Iterator iterator (ori); !iterator.isNil (); ++iterator)
    {
        actual.emplace(iterator.key (), iterator.value());
    }
```

**Comment by hcaihao** [comment]
Got it, Thank you!
