### ISSUE TITLE
#165/#166 broke assigning table values from C++

### ISSUE THREAD

**Issue by jquesnelle** [vinniefalco/LuaBridge#171]
The changes made by #165 and #166 have the side effect that you can't actually change any table values from C++. A simple test case:

```c++
TEST_F(LuaRefTests, ChangingTableValues)
{
	runLua("value = {a = 5}");
	auto value = luabridge::getGlobal(L, "value");
	ASSERT_TRUE(value.isTable());
	ASSERT_TRUE(value["a"].isNumber());
	ASSERT_EQ(5, value["a"].cast <int>());
	value["a"] = 6;
	ASSERT_EQ(6, value["a"].cast <int>());
}
```

This test case passes at b3792fd but fails on fc224ab.

**Comment by dmitry-t** [comment]
The proxy class is to be returned back. A common LuaRef/Proxy base class/class template may be used to eliminate the code duplication.

**Comment by merlinblack** [comment]
Assigning values to table elements is pretty much all the proxy is for. Originally it was importaint to 'hide' the proxy class, so it would not get used directly. But now deriving from a base class to prevent code duplication is far more important I think. It's what I've now done in my new re-write of LuaRef.
