### ISSUE TITLE
How to addFunction a class member method?

### ISSUE THREAD

**Issue by hcaihao** [vinniefalco/LuaBridge#174]
`void SmartContract::ShakeWindow();`

`.addFunction("ShakeWindow", std::bind(&SmartContract::ShakeWindow, this))`

Get error:
Error	C2955	'luabridge::CFunc::Call': use of class template requires template argument list	SmartContract	e:\develop\2015\luabridge\source\luabridge\detail\Namespace.h	1083	1	

Error	C2976	'luabridge::CFunc::Call': too few template arguments	SmartContract	e:\develop\2015\luabridge\source\luabridge\detail\Namespace.h	1083	1

**Comment by dmitry-t** [comment]
C++1x is unsupported. This is stated in the README.md (as an advantage though).
The library has to be modernized.
See also #90.

**Comment by hcaihao** [comment]
The "luabind" have a tag_function to implement this without c++1x:

`luabind::def("test", luabind::tag_function<void()>(boost::bind(&Game::Test, this))),`

Can you copy it?

**Comment by dmitry-t** [comment]
It uses the boost library which is really huge. While the LuaBridge is intended to be dependency free.
I will better add support for `std::function` (and so for `std::bind` and lambdas).

**Comment by hcaihao** [comment]
Is there any tricks to implement this with current luabridge?

**Comment by dmitry-t** [comment]
It needs some time for implementation and testing.
Right now, if the instance of your `SmartContract` class is globally accessible (through some global variable or a singleton or some context or registry), you can register the `ShakeWindow` as a simple function (via `addFunction`).
```C++
void ShakeWindow() {
  g_smartContractInstance.ShakeWindow();
}
...
.addFunction("ShakeWindow", ShakeWindow);
```

**Comment by hcaihao** [comment]
got it, thank you!
