### ISSUE TITLE
Both LuaBridgeTests51 and LuaBridgeTests52 fails in same place.

### ISSUE THREAD

**Issue by Grandmother** [vinniefalco/LuaBridge#176]
/home/kovtyukhrd/sources/LuaBridge/Tests/Source/Tests.cpp:283: Failure
Expected equality of these values:
  10
  outer.data.data
    Which is: 1
[  FAILED  ] LuaBridgeTest.ClassProperties (1 ms)
...
[  PASSED  ] 27 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] LuaBridgeTest.ClassProperties

I suddenly can't figure out if it's good or not. If it's good, may be it's better to remove this test from repo?

**Comment by Grandmother** [comment]
Tests fails at least from 916c78b.

**Comment by dmitry-t** [comment]
This test indicates the place that needs to be improved - a property getter returns a newly created object, so a subsequent chain call does not affect the original object. Corresponding tickets are tagged with "return-by-value".

**Comment by Grandmother** [comment]
Ok, thanks.

**Comment by dmitry-t** [comment]
Disabled the test.
