### ISSUE TITLE
how can LuaBridge pass a pointer to an object from one function to another?

### ISSUE THREAD

**Issue by egor230** [vinniefalco/LuaBridge#179]
Please tell me how in LuaBridge to pass a pointer to an object from one function to another?

```C++
using namespace luabridge;
struct a {
    int x;
    a(int x)
    {
        this->x = x;
        cout << "call constructor with parameters\n" <<  endl;
    }
    void get() const /* время жизни lua.*/ {cout << x << endl;  }
    ~a() { cout <<"desctor\n"  << endl; }
};
a* create(){
    a b(56);
    return &b;
}
void pri(a *b, lua_State* L) {
    b->get();  
}        

int main() {
    lua_State *L = luaL_newstate();
    luaL_openlibs(L);
    getGlobalNamespace(L).addFunction("create", create)
    .addFunction("pri", pri);

    luaL_dofile(L, "main.lua");
    lua_pcall(L, 0, 0, 0);    }
```

**Comment by egor230** [comment]
Thank you very much for responding to dmitry-t so quickly. There is very little information on LuaBridge. For some reason, this option leads to an error.  It is necessary that the function returns an object of the class, another accepted it by calling its method.
lua 
a=create()
pri(a)

this was done through the lua api.

`

struct a { int x = 3010;
a () { this->x = x; } / / default constructor
	void show () { cout < < "x =" < < x < endl; } 
};

int create (lua_State* L) {// structure object creation Function.
	void * st = lua_newuserdata(L, sizeof (a));/*this function allocates a new memory block with the specified size,*/
	new (st) a ();// Allocate memory for use. data.
	luaL_getmetatable (L, "mt"); /* sends a value to the meta-table stack at a given acceptable index.*/
	lua_setmetatable (L, 1);//gets a table from the stack and its mouth as a new meta-table for a value with a given valid index.
	return 1;};

int destroy (lua_State* L) {// the Function calls the destructor on the object.
	a* st = (a*)lua_touserdata (L, 1);/* If the value in this acceptable index is complete user data.*/
	st - >~a();//call the destructor method.
	return 0;};

int show(lua_State* L) {
	a* st = (a*)lua_touserdata (L, -1);
	st - >show();
	return 0;};

int main() {
	lua_State* L = luaL_newstate();
	lua_newtable(L);
	lua_pushcfunction (L, create); / / Ust pointer to C++ function and creates inside Lua
	lua_setglobal (L, "get"); //gets the value from the stack and the value of the global name.
	lua_pushcfunction (L, show);
	lua_setglobal (L, "show"); //gets the value from the stack and the value of global name.
	luaL_newmetatable (L, "mt");/*int luaL_newmetatable (lua_State * L, const char * t); */
	lua_pushstring(L, " _ _ gc");
	lua_pushcfunction (L, destroy);
	lua_settable (L, 2);
    luaL_dofile(L, " main.lua"); / / Loads and runs the specified file. the file in which everything happens.
	lua_close (L); / / close state
	cin.get ();//the program is waiting for the character to be entered.
return 0;
}
Lua

a = get()
show(a)
`
How to do this in LuaBridge?

**Comment by dmitry-t** [comment]
Oh, I see. So the question is about the class registration.

There is [LuaBridge maual](http://vinniefalco.github.io/LuaBridge/Manual.html). There you can also find more useful examples.

For your 1st case (class `a` and `pri` function) you should register the class `a`, its constructor (so you actually don't need the `create()` function) and the `get()` member function. Also you should register the function `pri()`, e.g. in the global namespace.
```C++
getGlobalNamespace (L)
   .beginClass <a> ("a")
      .addConstructor <void (*) (int)> ()
      .addFunction ("get", &a::get)
    .endClass ()
    .addFunction ("pri", pri)
 .endNameSpace ();
```
Note that the function is without the `lua_State*` parameter in such case:
```C++
void pri(a *b) {
    b->get();  
} 
```

I hope this helps.

BTW, it would be good if next time you ask questions on some forum (e.g. [stackoverflow.com](stackoverflow.com)), because github issue tracker is really not the best place for them :)

**Comment by egor230** [comment]
Thank you very much for the answer. Unfortunately, the code generates Error (active) E0135 class "luabridge::Namespace" and does not contain member "endNameSpace" lua api c++:\c++\lua api c++\Source.cpp 35	
I read several times the reference manual it is not quite accurate
 For example, the Code I have gives 0, not 10 like it says in the manual.
` 
static float staticVar;

int globalVar;
std::string stringProperty;
std::string getString() { return stringProperty; }
void setString(std::string s) { stringProperty = s; }

int foo() { return 42; }
void bar(char const*) { }
int cFunc(lua_State* L) { return 0; }
int main() {
	lua_State *L = luaL_newstate();
	luaL_openlibs(L);
	getGlobalNamespace(L) .beginNamespace("test")
	   .addVariable("var1", &globalVar)
		.endNamespace();
	cout <<globalVar  << endl;
	luaL_dofile(L, "main.lua");
	lua_pcall(L, 0, 0, 0);
}


Lua


test        -- a namespace
test.var1 =10   -- a lua_Number variable
-- test.var2   -- a read-only lua_Number variable
-- test.prop1  -- a lua_String property
-- test.prop2  -- a read-only lua_String property
-- test.foo    -- a function returning a lua_Number
-- test.bar    -- a function taking a lua_String as a parameter
-- test.cfunc  -- a function with a variable argument list and multi-return
`





 there are no video lessons on YouTube.  He recorded a lua api for c++. luabridge is a very cool thing, she really needs me to build it in GTA Vice city
 the function creates a class object. We return a pointer to a class object from a function and pass it to another function.
 I will be very grateful if you do not give an example of how to send and receive fulluserdata in luabridge.
On this forum, asked questions, well, never got answers

**Comment by dmitry-t** [comment]
It's a different question. There even two questions. Every problem should have its own github issue to avoid confusing other users. And I strictly recommend you to ask questions on the stackoverflow site.
