### ISSUE TITLE
Please tell me how to pass the string wchar t luabridge to the stack and get from the stack?

### ISSUE THREAD

**Issue by egor230** [vinniefalco/LuaBridge#182]
Please tell me how to pass the string wchar t luabridge to the stack and get from the stack?

`    wchar_t const x[] = TEXT("abcd");// массив char.
	wcout << x << endl;// выводится firts
	Stack<wchar_t const[]>::push(L, x);// отправить в стек и получить из стека можно 
	WCHAR y = Stack<wchar_t const>::get(L, -1); //получить из стека
	wcout << y << endl;// выводится firts
`

**Comment by dmitry-t** [comment]
Could you please translate the text to English?
Also, please use the following snippet for C++ code samples:
\`\`\`C++
// Code
\`\`\`
