### ISSUE TITLE
How to pass lua function as parameter to C++ function?

### ISSUE THREAD

**Issue by kelvinh** [vinniefalco/LuaBridge#183]
Assume there is a C++ function `DoSomething` exposed to Lua with the following code:

```
luabridge::getGlobalNamespace(L).addFunction("DoSomething", &DoSomething);
```

And I call this function in Lua with the following code:

```
DoSomething(function ()
    print('hello world')
end)
```

As you see, there is a Lua callback function taken as the parameter, so, the problem is, how should I define the C++ function?

```
void DoSomething(<???> lua_callback) { // <-- What should it be at <???> ?
    // do something here
    // call lua_callback
}
```

Thanks!

**Comment by dmitry-t** [comment]
Have you tried
```C++
void DoSomething(luabridge::LuaRef lua_callback) { // <-- What should it be at <???> ?
    // do something here
    // call lua_callback
}
```

**Comment by kelvinh** [comment]
Wow, that's indeed what I need. I will go through the manual in detail. Thanks!
