### ISSUE TITLE
bind glm::vec3

### ISSUE THREAD

**Issue by Hperigo** [vinniefalco/LuaBridge#185]
Hi, I’m trying to bind glm’s ::vec3 to lua using lua bridge. 
I’ve managed to get something using a VectorHelper described in the documentation

```
    struct VecHelper
    {
        template <unsigned index>
        static float get (glm::vec3 const* vec)
        {
            return (*vec)[index];
        }

        template <unsigned index>
        static void set (glm::vec3* vec, float value)
        {
            (*vec)[index] = value;
        }
    };

```

And the binding: 

   ```
     .beginNamespace("glm")
        .beginClass<glm::vec3>("vec3")
        .addConstructor<void(*)(float, float, float)>()
        .addProperty ("x", &VecHelper::get <0>, &VecHelper::set <0>)
        .addProperty ("y", &VecHelper::get <1>, &VecHelper::set <1>)
        .addProperty ("z", &VecHelper::get <2>, &VecHelper::set <2>)
        .endClass()
        .endNamespace();
```

The result in lua (works fine): 

```
a = glm.vec3(10, 10, 10)
b = glm.vec3(20, 20, 20)
print(a.x)
```

But I’m having some trouble implementing operators or even a simple __tostring, see below 
```
    struct VecHelper
    {

   ...

	//does not work as a “__tostring” metatable
        static std::string toString( glm::vec3 const * a ){
            return to_string(a->x) + "," + to_string(a->y) + ","  + to_string(a->z);
        }
};

...

        .beginNamespace("glm")
        .beginClass<glm::vec3>("vec3")
        .addConstructor<void(*)(float, float, float)>()
        .addProperty ("x", &VecHelper::get <0>, &VecHelper::set <0>)
        .addProperty ("y", &VecHelper::get <1>, &VecHelper::set <1>)
        .addProperty ("z", &VecHelper::get <2>, &VecHelper::set <2>)
        .addFunction("__tostring", &VecHelper::toString)
        .endClass()
        .endNamespace();

```
that 👆 wont compile, the error is: 
``` No member named 'isConstMemberFunction' in 'luabridge::FuncTraits<std::__1::basic_string<char> (*)(const glm::tvec3<float, glm::packed_highp> *), std::__1::basic_string<char> (*)(const glm::tvec3<float, glm::packed_highp> *)>'```

does anyone have any tips on how to achieve that?  I know that there are some security issues with metatables that luabridge solves, by I was wondering if that's the problem I'm encountering or if there's anyway to bypass that

thanks!

**Comment by dmitry-t** [comment]
Unfortunately, Lua metamethods like `__add`, `__index` or `__tostring` are unsupported for now.
So far I suggest explicit function invocations
```C++
.addFunction ("toString", &VecHelper::toString)
```
```Lua
print (a.toString ())
```

**Comment by Hperigo** [comment]
got it! thanks for the help!

**Comment by m1k0s** [comment]
> Unfortunately, Lua metamethods like `__add`, `__index` or `__tostring` are unsupported for now.
> ...

Is this really true (as in, has something changed in recent version of luabridge to remove the functionality)?

I have always used:

`	.addFunction("__tostring", &maths::Vector2::ToString)
	.addFunction("__eq", &maths::Vector2::operator==)
	.addFunction("__unm", &maths::Vector2::operator-)
	.addFunction("__add", (maths::Vector2 (*)(const maths::Vector2&, const maths::Vector2&))&::operator+)
	.addFunction("__sub", (maths::Vector2 (*)(const maths::Vector2&, const maths::Vector2&))&::operator-)
	.addFunction("__mul", (maths::Vector2 (*)(const maths::Vector2&, const maths::Vector2&))&::operator*)`

**Comment by dmitry-t** [comment]
You are right, and I wasn't. Recently I added [tests for meta-methods](https://github.com/vinniefalco/LuaBridge/blob/d07c50e76f65921b87bf70c806d5bafa20c0cdb0/Tests/Source/ClassTests.cpp#L554).
The reason why they work is that all the functions are stored in userdata metatables where the Lua finds them directly (`__index` metamethod is not invoked iin such cases).

**Comment by dmitry-t** [comment]
@Hperigo the real problem was that here
```
        .addFunction("__tostring", &VecHelper::toString)
```
you used a proxy function for registration of a class method which is not supported so far.

Fortunately I'm preparing an update with support of such cases (for C++11 compilers only which shouldn't be an issue in 2019).

**Comment by dmitry-t** [comment]
The update that enables proxy functions for methods: #193.
