### ISSUE TITLE
What's the best way to deal with garbage collection? 

### ISSUE THREAD

**Issue by Hperigo** [vinniefalco/LuaBridge#190]
Hi, I wrote an application that uses luabridge to update the color of some objects on the screen. The app is eating a lot of memory, and I’m not sure what is best way to collect garbage.

My code structure is something like this: 
Luabridge registers a couple of objects ( like color, vector3, etc..  )
Calls a lua function ( using lua bridge ) every frame for every object in the screen ( around 250 ). 

pseudo-ish code: 
```
App::setup() { // get’s called once
        myScript.loadScript(“script.lua”); 
}
	
App::update(){  // get’s called every frame
	lua_State* L =  myScript.getGlobalState();
        luabridge::LuaRef updateFn = luabridge::getGlobal( L, "updatePendant");
        for( auto& pendant : getPendants() ){
            updateFn(pendant->_id, *pendant ); // pass a pendant pointer to the lua function and modify it there.
        }
}
```

The `myScript` object is just a wrapper in charge of loading and compiling the script, basically `luaL_loadfile` and `lua_pcall` 

Here’s a graph of the application memory, when the lua script is called, the memory just builds up.

![image](https://user-images.githubusercontent.com/3333460/56380441-8a2ca780-61e8-11e9-86dd-7cfc2b3b4228.png)

calling `collectgarbage` at the end of the update cycle solves that. But is that the standard way of doing things? Do I have to explicitly call collectgarbage every time a function is ran/end of update?   

Thanks

**Comment by dmitry-t** [comment]
Obviously, it's up to Lua implementation when to call the garbage collector.

It would be interesting to take a look at the graphs where the `collectgarbage` is called.

So far it's unclear what is the "pendant", is it heavy or not?
Also I'd check how many temporary objects created.
Most probably there are many objects with lifetime controlled by Lua.
If your objects lifetime is controlled by C++ you don't depend on the GC so much.

**Comment by Hperigo** [comment]
Hi, thanks for the reply. 

_It would be interesting to take a look at the graphs where you call collectgarbage in the end of the cycle._
there you go:
<img width="725" alt="Screen Shot 2019-04-22 at 9 14 38 AM" src="https://user-images.githubusercontent.com/3333460/56500396-fbb66f80-64e0-11e9-8f51-7844cbf11521.png">


_So far it's unclear what is the "pendant", is it heavy or not_

```
    glm::vec3 pos;
    glm::ivec2 pixelBufferPos;
    
    // json settings ----
    int port = -1;
    int _id = -1; // id from json
    int cableId   = -1; // id from json
    int cableTriplet = -1;
    float depth  = -1.f;
    
    // network data -----
    float attackAmt;
    float trafficAmt;
    
    Splitter* _spliter;
    WhiteWingManager* _whiteWingManager;
```

_Most probably there are many objects with lifetime controlled by Lua._
yeah, the lua function get's called every frame for each pendant. Because I'm passing a pointer to a pendant on the lua function call, the binding is prob. creating some temp objects.

_BTW, how much memory exactly use your application?_
around ~25mb

**Comment by dmitry-t** [comment]
> yeah, the lua function get's called every frame for each pendant. Because I'm passing a pointer to a pendant on the lua function call, the binding is prob. creating some temp objects.

Indeed, pointers stored as fulluserdata, and so depend on GC to be freed. I'll take a look if any memory optimization can be done here.

**Comment by Hperigo** [comment]
nice! thanks for the help

**Comment by dmitry-t** [comment]
It looks like it's not possible to use Lua light userdata instead of full userdata for object pointers, because light userdata do not have individual metatables.
> It is a value (like a number): you do not create it, it has no individual metatable, and it is not collected (as it was never created). A light userdata is equal to "any" light userdata with the same C address.

From here: https://www.lua.org/manual/5.1/manual.html#lua_pushlightuserdata
See also: https://www.lua.org/pil/28.5.html

**Comment by dmitry-t** [comment]
It looks like it's not possible to use Lua light userdata instead of full userdata for object pointers, because light userdata do not have individual metatables.
> It is a value (like a number): you do not create it, it has no individual metatable, and it is not collected (as it was never created). A light userdata is equal to "any" light userdata with the same C address.

From here: https://www.lua.org/manual/5.1/manual.html#lua_pushlightuserdata
See also: https://www.lua.org/pil/28.5.html
