### ISSUE TITLE
please help me to determine the index of the class is on the stack?

### ISSUE THREAD

**Issue by egor230** [vinniefalco/LuaBridge#202]
please help me to determine the index of the class is on the stack?
The function takes an object class, you need what is the object of the class?

```

int checkerror(lua_State* L, const char* file) {
	int status = luaL_loadfile(L, file);// проверка есть ли ошибки.
	try {
		if (luaL_dostring(L, file) == LUA_OK) {
			return 0;
		}
		else {
			string x = lua_tostring(L, -1);
			throw x;
			return 0;
		}
	}
	catch (string x) {
		cout << x << endl;
		//luaL_error(L,"error"); 
		return 0;
	}
};
struct a {
	int x = 302;
	a(int x) { this->x = x;  }
	void get() const /* время жизни lua.*/ { cout << x << " " << endl; }
};

struct b{
	void show() const /* время жизни lua.*/ { cout << "show " << endl; }
	
};

void pri(lua_State* L) {
	try
	{
		a* b1 = (a*)Userdata::getExact<a>(L, 1);
		b1->get();
		try	{
			b* c = (b*)Userdata::getExact<b>(L, 1);
			c->show();
		}
		catch (std::exception& e)	{	}
	}
	catch (std::exception& e)
	{
	}
};

const char* LUA = R"(
a=st(21)
b1 = st1()
pri(b1)

)";
int main(int argc, char* argv[]) {
	lua_State* L = luaL_newstate();
	luaL_openlibs(L); getGlobalNamespace(L)// получить глоб место.
		.beginClass<a>("st")// имя класса в lua.
		.addConstructor<void(*)(int)>()// конструктор класса.
		.addFunction("get", &a::get)// метод класса
		.endClass()// закрыть регистрацию класса. 
		.beginClass<b>("st1")// имя класса в lua.
		.addConstructor<void(*)()>()// конструктор класса.
		.addFunction("show", &b::show)// метод класса
		.endClass()// закрыть регистрацию класса. 
		.addFunction("pri", &pri);// Регистрация функции.

	checkerror(L, LUA);

	return 0;
};
```

**Comment by dmitry-t** [comment]
Sorry, I don't quite understand your question.
What exactly do you want to get or print?

**Comment by egor230** [comment]
> Sorry, I don't quite understand your question.
> What exactly do you want to get or print?
sorry for the inaccurate question. How do you know LuaBridge on the stack is the instance that is class a and not class b?

**Comment by dmitry-t** [comment]
Ok, so you want to check whether a userdata instance on the stack represent some specific class, right?

There was a proposal for `LuaRef:isa<T>` but it was not merged for some reasons.

If your classes has a common base, you can add e.g. a pure virtual `getName ()` (or rather `toString ()` because you intent to dump some object information) to the base class.
Another option is to define a `__tostring` function for your classes, so you're able to call `string.format ('a=%s, b1=%s', a, b1)` in `Lua`.

**Comment by egor230** [comment]
thank you very much for Your reply.
the described method does not suit me.
I need a check is in the stack, full user data that belong to class A?
Can this function determine is the stack full user data class A?

help me, please.

```
int pri(lua_State* L) {
	a* c;
	bool canBeConst;

	luabridge::Userdata::getClass(L, 1, c, canBeConst);
		cout << canBeConst << endl;
		
		return 0;
};

const char* LUA = R"(
a = st(21)

pri(a)

)";
int main(int argc, char* argv[]) {
	lua_State* L = luaL_newstate();
	luaL_openlibs(L); getGlobalNamespace(L)// получить глоб место.
		.beginClass<a>("st")// имя класса в lua.
		.addConstructor<void(*)(int)>()// конструктор класса.
		.addFunction("get", &a::get)// метод класса
		.endClass()// закрыть регистрацию класса. 
		.beginClass<b>("st1")// имя класса в lua.
		.addConstructor<void(*)(int)>()// конструктор класса.
		.addFunction("show", &b::show)// метод класса
		.endClass()// закрыть регистрацию класса. 
		.addFunction("pri", pri);// Регистрация функции.

	checkerror(L, LUA);

	return 0;
};
```

**Comment by dmitry-t** [comment]
Is #44 what you need (something like `Stack <MyClass>::is_a (L, -1)`)?

**Comment by egor230** [comment]
> Является [# 44](https://github.com/vinniefalco/LuaBridge/issues/44) , что вам нужно (что - то вроде `Stack <MyClass>::is_a (L, -1)`)?

thank you very much dear Dmitry, you can use an example for a clearer understanding

**Comment by dmitry-t** [comment]
I'm just guessing that the `is_a` is what you need, however it's better if you confirm that.

**Comment by egor230** [comment]
> Я просто предполагаю, что `is_a`это то, что вам нужно, но лучше, если вы подтвердите это.
how to use it? can you give me an example to understand

**Comment by dmitry-t** [comment]
It it was implemented, it would probably look like:
```C++
void pri (lua_State* L)
{
  if (Stack <a>::is_a (L, 1))
  {
    Stack <a*>::get (L, 1)->get ();
  }
  else if (Stack <b>::is_a (L, 1))
  {
    Stack <b*>::get (L, 1)->show ();
  }
}
```

**Comment by egor230** [comment]
thank you very much
