### ISSUE TITLE
Register overloaded static methods

### ISSUE THREAD

**Issue by ThisMeansYou** [vinniefalco/LuaBridge#203]
Hi! I found somewhere in the previous comments a way to overload methods, I was thinking is there a way to overload static methods?

Because the way of overloading methods doesn't seem to work for the static methods.
The example found:

```
class A {
public:
    int test(string s);
    int test(int s);
}

getGlobalNamespace (L)
  .beginNamespace ("asd")
    .beginClass<A>("A")
      .addConstructor <void (*)(void)> ()
      .addFunction("tests", (int (A::*)(string)) &A::test)
      .addFunction("testi", (int (A::*)(int)) &A::test)
    .endClass()
  .endNamespace ();
```

Thanks in advance for the help

**Comment by dmitry-t** [comment]
This is not related to the `LuaBrigde` :)

Anyway the type of a static class member function is the same as the type of an ordinary function. In your case it should be `int (*) (string)` not `int (A::*) (string)`.

**Comment by ThisMeansYou** [comment]
Thank you! that did solve my problem!
Just a further tiny question, in my C++ code I exposed the following code:
rand.get(int max) and rand.get(int min, int max)

When invoking from Lua, it seems like only the method exposed first "get(int max)"
gets called, even when executing: get(1, 10);

	for i = 1, 10 do
		print (rand.get(5, 5));
	end

It invokes the incorrect method

Exposing looks like this:
		getGlobalNamespace(L)
			.beginNamespace("test")
			.beginClass<Rand>("rand")
			.addConstructor<void(*)(void)>()
			.addStaticFunction("get", (int (*)(const int, const int)) &Rand::get)
			.addStaticFunction("get", (int (*)(const int)) &Rand::get)
		.endClass();

What am I missing out?

**Comment by dmitry-t** [comment]
The second "get" function overrides (hides) the first one.
`Lua` function overloading is not supported by `LuaBridge`.

There a couple of workarounds:
- In your previous case you registered overloaded functions under different names - that the 1st approach.
- The 2nd approach is to register a C-function (that takes `lua_State*` only) and handle arguments manually.

**Comment by ThisMeansYou** [comment]
Thank you, I think I’ll just use different names for the Lua functions.
