### ISSUE TITLE
LuaBridge Enumerations

### ISSUE THREAD

**Issue by ThisMeansYou** [vinniefalco/LuaBridge#204]
Hi there, 

I saw a post from 2016 about "exposing" an enum using LuaBridge [Right here](https://github.com/vinniefalco/LuaBridge/issues/127)

I created the following structure (added the template class in Stack.h), not sure how to implement it in my binder class at the moment. My attempt was as the following:

MyEnum.h:
enum class MyEnum
{
 A = 0,
 B = 1,
C = 2
}

Stack.h (LuaBridge):
template <typename T>
struct EnumWrapper {
    static inline
    typename std::enable_if<std::is_enum<T>::value, void>::type
    push(lua_State* L, T value) {
        lua_pushnumber(L, static_cast<std::size_t>(value));
    }

    static inline
    typename std::enable_if<std::is_enum<T>::value, T>::type
    get(lua_State* L, int index) {
        return static_cast<T>(lua_tointeger(L, index));
    }
};

Binder.cpp:

template<>
struct luabridge::Stack<MyEnum> : public EnumWrapper<MyEnum>
{
	
};

Thanks in advance!

...
... 
Now how do I bind my enum to Lua?

**Comment by dmitry-t** [comment]
The enum specialization must be defined in the `luabridge` namespace:
```C++
namespace luabridge {

template <>
struct luabridge::Stack <MyEnum> : EnumWrapper <MyEnum>
{
};

} // namespace luabridge
```

BTW it's not a good idea to put the `EnumWrapper` into the `LuaBridge` header.

**Comment by dmitry-t** [comment]
[EnumWrapper class example](https://github.com/vinniefalco/LuaBridge/blob/baba8b6a95a7aa92996e86a0846750aac9a57274/Tests/Source/IssueTests.cpp#L147)

**Comment by dmitry-t** [comment]
Closing the issue because there is a full answer and code example provided.
Please feel free to reopen this issue, or create a new one in case of further questions.

**Comment by Zero-Fanker** [comment]
> [EnumWrapper class example](https://github.com/vinniefalco/LuaBridge/blob/baba8b6a95a7aa92996e86a0846750aac9a57274/Tests/Source/IssueTests.cpp#L147)

but i want to use a word(instead of a number) to identity a certain enumeration, like 
```lua
function(input)
    if input == MyEnum.A
end
```
what should i do to make it work ?
