### ISSUE TITLE
Different function return types (derived class)

### ISSUE THREAD

**Issue by BlueMountainsIO** [vinniefalco/LuaBridge#211]
Let's say I have different classes that derive from a base class.

How do I specify a function that can return any class that derives from a base class?
Because when I do it like in the example below I will always just see the base class (MyBaseClass) in Lua and not the desired derived class that I returned.

```C++
RefCountedPtr<MyBaseClass> TestFunc(RefCountedPtr<SomeOtherClass> Object)
{
    if (...)
        return RefCountedPtr<MyParentClass>(new MyParentClass());
    else
        return RefCountedPtr<MySecondParentClass>(new MySecondParentClass());

    return nullptr;
}
```

```C++
luabridge::getGlobalNamespace(L)
    .beginClass<MyBaseClass>("MyBaseClass")
    .endClass()
    .deriveClass<MyParentClass, MyBaseClass>("MyParentClass")
    .endClass()
    .deriveClass<MySecondParentClass, MyBaseClass>("MySecondParentClass")
    .endClass();
```

I can't use ``push`` and a pure C function because the function arguments have specific userdata types as well.

Thank you!

**Comment by dmitry-t** [comment]
How do you know the C++ class in Lua code? Could you please post the code registering the classes?

**Comment by BlueMountainsIO** [comment]
It's pretty much the standard thing. I've added more code to the question, hope it helps.

**Comment by dmitry-t** [comment]
So how do you know what is the C++ class in your Lua code?

**Comment by BlueMountainsIO** [comment]
Hm sorry what do you mean? When someone calls ``TestFunc`` from Lua they will get a different class depending on the argument they pass to the function.

**Comment by dmitry-t** [comment]
I probably don't understand the intention.
Do you want the returned object to have a behaviour that depends on the TestFunc logic?

If a function returns a pointer to class A, it's always of type "pointer to A"; in C++ there is only one return type (static type). However the actual type (dynamic) may differ, it can be some derived class B. Then the class A should have some virtual functions, overridden in the class B. But it's pure C++ and isn't related to LuaBridge.

**Comment by BlueMountainsIO** [comment]
You can see in my example that the classes derive from each other. I could use ``luabridge::push(L, ...)`` to push the values on the Lua stack. But that would require to have ``TestFunc`` added with ``addCFunction`` and lua_State *L as the parameter. But I can't do that because as you can see ``TestFunc`` has an argument that I don't know to get manually from Lua.

**Comment by dmitry-t** [comment]
> TestFunc has an argument that I don't know to get manually from Lua.
There is `RefCountedPtr<SomeOtherClass>`, which can be retrieved with `Stack<RefCountedPtr<SomeOtherClass>::get(L, 1)`.

**Comment by BlueMountainsIO** [comment]
Thank you dimitry! This works well now:
```C++
int TestFunc(lua_State *L)
{
    auto Val = Stack<RefCountedPtr<SomeOtherClass>>::get(L, 1);

    if (...)
        push(L, RefCountedPtr<MyParentClass>(new MyParentClass()));
        return 1;
    else
        push(L, RefCountedPtr<MySecondParentClass>(new MySecondParentClass()));
        return 1;

    return 0;
}
```

**Comment by dmitry-t** [comment]
OK, since the case is rather specific, and there is a solution, closing the issue.
