### ISSUE TITLE
how to make the address of the class object in memory was constant?

### ISSUE THREAD

**Issue by egor230** [vinniefalco/LuaBridge#212]
Hello, everyone. can't check the class of an object on the stack? I don't have a method (Stack <a>:: is_a (L, 1))

how to make the address of the class object in memory was constant?
if you do begin Class<a const*>("st") throws an error.

```

struct a {
	int x = 302;
	a() { this->x = x; cout << "create object " << this << "\ncall default constructor\n" << endl; }


	void get() { cout << x << " " << endl; }
	~a() { cout << "desctor " << this << endl; }
};

int create(lua_State* L) {

	a* b = (a*)Userdata::get<a>(L, 1, false);
	cout << b << endl;
	int key = (int)b;
	cout << key << endl;

	Stack<a*>::push(L, b);
	return 1;
};
int pri(lua_State* L) {
	const void* t = lua_topointer(L, 1);
	cout << t << endl;

	return 0;
};
const char* LUA = R"(
    a=st()
    a1=create(a)
    pri(a1)

)";
int main() {
	lua_State* L = luaL_newstate();
	luaL_openlibs(L);


	getGlobalNamespace(L)// получить глоб место.
	.beginClass<a const*>("st")	// имя класса в lua.
	.addConstructor<void(*)()>() // конструктор класса.
	.addFunction("get", a::get)// метод класса
	.endClass()// закрыть регистрацию класса. 
	.addCFunction("create",  &create )	 // Регистрация функции.
	.addCFunction("pri", &pri);// Регистрация функции.

	checkerror(L, LUA);
	lua_close(L);// закрыть состояние
	return 0;
};

```

**Comment by dmitry-t** [comment]
> Hello, everyone. can't check the class of an object on the stack? I don't have a method (Stack :: is_a (L, 1))

This is another issue, and I wrote "if it was implemented I would look like" and asked if it's what you actually need.

There is no such thing as "const class".

You should understand that the const-ness in C++ is not physical, so there may be no difference between "const" and "non-const" memory. A programmer may always fool the compiler by using e.g. `const_cast`.

However LuaBridge distinguishes const and non-const objects. If you pass a const object reference, such an object will be read-only in Lua.

**Comment by dmitry-t** [comment]
> Hello, everyone. can't check the class of an object on the stack? I don't have a method (Stack :: is_a (L, 1))

This is another issue, and I wrote about "is_a" that "if it was implemented I would look like" and asked if it's what you actually need (and I think it's worth implementation).

**Comment by egor230** [comment]
Thank you very Much for your reply Dmitry.

My Idea was that there is an object address in memory that will be constant, that you can store it in a container for a class, and then check if it is in it.

**Comment by dmitry-t** [comment]
Sorry for not replying so long.

Actually I don't understand what you mean and you are trying to achieve, so I cannot answer.

What is an "address in memory that will be constant"? How do you suppose to store it in a container?

It's [always] nice to see some concept code, maybe pseudo-code.

**Comment by egor230** [comment]
thanks for the answer, I will wait for the opportunity to see the class in the stack

**Comment by dmitry-t** [comment]
#218

**Comment by dmitry-t** [comment]
The `Stack<>::isInstance ()` is in the master branch.
