### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by ghost** [vinniefalco/LuaBridge#213]
It doesn't actually do anything when running make -j. What version of cmake does it require?

**Comment by dmitry-t** [comment]
The CMake version requirement is stated in the 1st line of the top level CMakeLists.txt.
After you run cmake once, subsequent make invocations build unit tests.

And I believe this is mentioned in the readme.

But could you please describe what do you actually do?

**Comment by professorGIT** [comment]
Thank, I just did what the directions said on the github page. I am using a fedora and always had some strange issue with Cmake version, it uses a strange one.

**Comment by professorGIT** [comment]
Ok, it says cmake version 3.5, I have 3.14.5. Cmake is supposed to give a warning I think, but it doesn't. I don't know much abotu Cmake and find it confusing. I will see if I can get cmake 3.5 and build it.

**Comment by 1099511627776** [comment]
I confirm it did not build on my Ubuntu 14.04 either.
I've cloned repo, created build directory, changed CMake required version to 3.2 and built
CMake did not display any error but make -j did not do any output

**Comment by dmitry-t** [comment]
I see, the files for tests are not generated. #217 should fix this.

**Comment by dmitry-t** [comment]
Could you please try `master` once again?

**Comment by 1099511627776** [comment]
@dmitry-t 50/50 - I've managed to start building LuaBridge according to README.md
But it stoped on 14% with message error: extra qualification not allowed
```
hackers@hackers-Inspiron-3537:~/Devel/tmp/My_Lua/LuaBridge/build$ make
Scanning dependencies of target gtest
[  1%] Building CXX object third_party/gtest/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
Linking CXX static library libgtestd.a
[  1%] Built target gtest
Scanning dependencies of target gmock
[  3%] Building CXX object third_party/gtest/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
Linking CXX static library libgmockd.a
[  3%] Built target gmock
Scanning dependencies of target gmock_main
[  4%] Building CXX object third_party/gtest/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
Linking CXX static library libgmock_maind.a
[  4%] Built target gmock_main
Scanning dependencies of target gtest_main
[  6%] Building CXX object third_party/gtest/googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
Linking CXX static library libgtest_maind.a
[  6%] Built target gtest_main
Scanning dependencies of target JuceLibraryCode
[  7%] Building CXX object Tests/CMakeFiles/JuceLibraryCode.dir/JuceLibraryCode/BinaryData.cpp.o
Linking CXX static library libJuceLibraryCode.a
[  7%] Built target JuceLibraryCode
Scanning dependencies of target Lua51
[  9%] Building CXX object Tests/CMakeFiles/Lua51.dir/Lua/LuaLibrary5.1.5.cpp.o
Linking CXX static library libLua51.a
[  9%] Built target Lua51
Scanning dependencies of target Lua52
[ 11%] Building CXX object Tests/CMakeFiles/Lua52.dir/Lua/LuaLibrary5.2.0.cpp.o
Linking CXX static library libLua52.a
[ 11%] Built target Lua52
Scanning dependencies of target Tests51
[ 12%] Building CXX object Tests/CMakeFiles/Tests51.dir/Source/ClassTests.cpp.o
[ 14%] Building CXX object Tests/CMakeFiles/Tests51.dir/Source/IssueTests.cpp.o
/home/hackers/Devel/tmp/My_Lua/LuaBridge/Tests/Source/IssueTests.cpp:170:8: error: extra qualification not allowed [-fpermissive]
 struct luabridge::Stack <MyEnum> : EnumWrapper <MyEnum>
        ^
/home/hackers/Devel/tmp/My_Lua/LuaBridge/Tests/Source/IssueTests.cpp:171:1: error: explicit specialization of non-template ‘luabridge::<anonymous struct>’
 {
 ^
/home/hackers/Devel/tmp/My_Lua/LuaBridge/Tests/Source/IssueTests.cpp:172:1: error: abstract declarator ‘luabridge::<anonymous struct>’ used as declaration
 };
 ^
```

**Comment by dmitry-t** [comment]
Build fix is in #218.

**Comment by dmitry-t** [comment]
Could you please try the master?

**Comment by 1099511627776** [comment]
Yes now I've managed to build it.
Few link warnings:
Linking CXX executable Tests52L
libLua52.a(LuaLibrary5.2.0.cpp.o): In function `os_tmpname':
/home/hackers/Devel/tmp/My_Lua/LuaBridge/Tests/Lua/Lua.5.2.0/src/loslib.c:107: warning: the use of `tmpnam' is dangerous, better use `mkstemp'

But all was built

**Comment by dmitry-t** [comment]
These are warnings from Lua implementation, you can ignore them.
Closing the issue as solved.

**Comment by scollet1** [comment]
Build stalling at 89% on Linux Mint 19 when I run `make -j` on master
I have 4GB of memory, no other intensive applications running, and have to hard restart my system.
What could contribute to this?

**Comment by dmitry-t** [comment]
This doesn't look like related to LuaBridge anyhow.
But I observe such issue

**Comment by dmitry-t** [comment]
The problem doesn't seem to be related to LuaBridge.
But I observe such issue on my laptop (Ultrabook) when run `make -j`.
Could you try `make -j4` (i.e. run less build processes)?
