### ISSUE TITLE
Copying LuaRef from one state to another

### ISSUE THREAD

**Issue by misticniVrac** [vinniefalco/LuaBridge#220]
Hello,
I'm trying to copy tables from one lua_State to another, using LuaRef.

First i start by creating new LuaRef in B state, and then iterate trough A state LuaRef table casting and copying fields.
Something like this 
```c++
LuaRef res = newTable(L);
for(Iterator iterator(ref); !iterator.isNil(); ++iterator)
        {
                switch(iterator.value().type())
                {
                        case LUA_TNIL:
                                break;
                        case LUA_TNUMBER:
                                res[iterator.key()]=
                                        iterator.value().cast<lua_Number>();
                                break;
                        case LUA_TSTRING:
                                res[iterator.key()]=
                                        iterator.value().cast<std::string>();
                                break;
                        case LUA_TTABLE:
                                res[iterator.key()]
                                        = l_copy(L,iterator.value());//recursion
                                break;
            }
}
```
But i also want to copy Userdata.
I can do something like this 

```c++
res[iterator.key()] = iterator.value().cast<Vector2>();
```
But i have to specify cast type and i don't want to do that since i have multiple registered classes.
I'm quite new to this lib, and probably doing something wrong.
Is there a way to get Userdata without casting ? 
Is there maybe another way of achieving this?

Thank you for your help.

**Comment by dmitry-t** [comment]
Will #218 solve your issue?

**Comment by misticniVrac** [comment]
Yes, that will do it, thank you. 
Is there another way of passing data between states?

**Comment by dmitry-t** [comment]
The PR has been merged to master.
As for your question, I don't have ideas right now.
BTW, what is the purpose of moving data between states?

**Comment by misticniVrac** [comment]
I'm trying to make a small game engine with lua.The idea right now is to give each entity its own state with lua scripts acting as components.

**Comment by dmitry-t** [comment]
This sounds unusual to me.
All your instances probably want to _interoperate_ with each other, so I'd expect that they should belong to a single state.

**Comment by misticniVrac** [comment]
I'm still experimenting with ECS implementation, in the end i may put everything under one state.
