### ISSUE TITLE
TypeListValues passed both by value and reference in FuncTraits.h

### ISSUE THREAD

**Issue by sillykelvin** [vinniefalco/LuaBridge#221]
Hi, we use LuaBridge in our project, it's awesome! However there is a little issue reported by our linter tool, that `TypeListValues` passed by value as function parameter might affect performance in file `FuncTraits.h`.

We checked the file, and get a little confused: some `TypeListValues` are passed by value, such as [here](https://github.com/vinniefalco/LuaBridge/blob/24f1877f967cc138c780ed78a23e03a490a9aec9/Source/LuaBridge/detail/FuncTraits.h#L287) and [here](https://github.com/vinniefalco/LuaBridge/blob/24f1877f967cc138c780ed78a23e03a490a9aec9/Source/LuaBridge/detail/FuncTraits.h#L274), and some are passed by reference, such as [here](https://github.com/vinniefalco/LuaBridge/blob/24f1877f967cc138c780ed78a23e03a490a9aec9/Source/LuaBridge/detail/FuncTraits.h#L68) and [here](https://github.com/vinniefalco/LuaBridge/blob/24f1877f967cc138c780ed78a23e03a490a9aec9/Source/LuaBridge/detail/FuncTraits.h#L100).

So my question is, is it by design or it's just typos? Should we follow our linter's advice, make all `TypeListValues` passed by reference to improve performance?

Thanks for the great project!

**Comment by dmitry-t** [comment]
> is it by design or it's just typos?

Those may be typos.
I have to make changes and run tests on several platforms to make sure nothing is broken.
But you also can make a change, test it (on your project) and contribute anytime. Please feel free to do so.

**Comment by dmitry-t** [comment]
Have I missed anything? #223.
