### ISSUE TITLE
Share data between Lua scripts and Lua states

### ISSUE THREAD

**Issue by bgospodaru** [vinniefalco/LuaBridge#222]
I've been trying to accomplish some sort of global map which can be accessed by multiple Lua scripts.
Here is a minimal example of what I'm trying to achieve.

First script:
```Lua
mynamespace.context.set("key", "value")
local v = mynamespace.context.get("key")

local t = {}
t["mytable"] = 2
mynamespace.context.set("another key", t)
```

Second script:
```Lua
print(mynamespace.context.get("key")) -- should print "value"
print(mynamespace.context.get("another key")["mytable"]) -- should print 2
```

I'm using separate Lua states because I'm also working with threads. Obviously enough, if I store a LuaRef and try to access it from the other script I'll get a read access violation exception (because the first lua state does not exist anymore).

If I use a
```
map<string, string>
```
then everything is ok, but that's only because I actually make a copy of the contents inside LuaRef. The downside of this is that I can only store strings or if I use std::variant probably a bunch of other basic types, but not lua tables (unless I'm missing something).

My question is, how can I store a
```
std::map<std::string, type_that_can_hold_any_lua_type> my_map;
```
inside my c++ code and access it from any Lua script/state without losing data (because of Lua's garbage collection). In other words, a global generic map.

**Comment by dmitry-t** [comment]
>print(mynamespace.context.get("key")) -- should print "value"
>print(mynamespace.context.get("another key")["mytable"]) -- should print 2
What does make you think so? A Lua state is a sandbox which has its own variables independent on other states.

Every LiaBridge function accepts a Lua state parameter exactly because there are no sharing between states.

Still you can share the C++ data between states using the LuaBridge. You just have to register all classes, functions etc several times, ones per a state. Th

**Comment by bgospodaru** [comment]
I don't think you understand my question. I deliberately want a global map inside C++ which different lua states can access and modify.

**Comment by dmitry-t** [comment]
Yet I think I've understood your question :)
As I wrote, just register every C++ thing in every Lua state :)
NB. Of course, you have also to care about concurrent access in C++ code because Lua has no notion of concurrent access.

**Comment by bgospodaru** [comment]
Yes, that's indeed what I've ended up doing. My problem in particular was with mapping lua types to c++ types. Especially mapping the table. I think sol library solves this problem (what I mean by that is that it lets you copy a lua table to a c++ map). But I haven't found a way of doing this with LuaBridge (correct me if I'm wrong) and I think I have to do it manually.

One other problem that may arise is copying a lua function to a std::function. But I haven't looked into it yet. Thanks for the suggestions and if you have any more tips about my problems please do share!
