### ISSUE TITLE
getLocal function?

### ISSUE THREAD

**Issue by Sven65** [vinniefalco/LuaBridge#237]
In LuaBridge, there's currently only the `getGlobal` function for getting data from lua scripts, and that data has to be placed in the global lua state, from what I've been able to read.

Is there some equivalent of a `getLocal` function to get a `LuaRef` from a single file, or do I need to setup a new LuaState for each one? If so, how do I share data between them?

As an example, let's say I've got two files;

File 1:

```lua
local scriptData = {
    name = "File 1"
}
```

File 2:

```lua
local scriptData = {
    name = "File 2"
}
```

I'd like some way of loading them, and getting the `local scriptData` from each script in my C++ code.

Thanks!

**Comment by dmitry-t** [comment]
You cannot access a local variable from LuaBridge.
You can introduce a global variable instead or pass a local variable into a function.
This is not a LuaBridge limitation: https://stackoverflow.com/questions/22776420/how-could-i-access-local-variables-or-call-local-functions-in-lua-scripts-from-c

**Comment by Sven65** [comment]
Alright, thanks!
