### ISSUE TITLE
Compiling the library from objective C errors about Nil

### ISSUE THREAD

**Issue by kunitoki** [vinniefalco/LuaBridge#241]
`Nil` is a private keyword of objective-c, if i include luabridge from a .mm file, i get compilation errors.

**Comment by kunitoki** [comment]
This is fixed, together with a bunch of other things in 3.0 > https://github.com/kunitoki/LuaBridge

**Comment by dmitry-t** [comment]
OK, so you've decided to make a fork. And there were 268 forks before :)
I guess if you want people to use your version you should better contribute into the existing repository. Whose who want something fresh will probably migrate to `sol2` or `sol3`.
BTW, if there are no breaking API changes, it should still be 2.x. (Sorry I didn't get enough time to learn the differences, but most of them look like implementation changes).

**Comment by kunitoki** [comment]
yeah i need to maintain it separately

**Comment by kunitoki** [comment]
i still plan on doing some more work and simplifying the api

**Comment by kunitoki** [comment]
i'm one of the 269 indeed 🥇

**Comment by dmitry-t** [comment]
IMO it doesn't matter whether it's a fork or not, and the main idea is to help other people.
