### ISSUE TITLE
Script name

### ISSUE THREAD

**Issue by P45H3** [vinniefalco/LuaBridge#244]
How to get the name of the script that called the function from C++?

**Comment by dmitry-t** [comment]
There is no direct way to do so, but still the answer depends on your needs.
So what's your scenario?

**Comment by P45H3** [comment]
The lua script calls a function from c ++. I need to find out the name of the script that called it in this C ++ function.

**Comment by P45H3** [comment]
I load 10 scripts via luaL_dofile. Each one calls one function from C ++. It is necessary inside this function to determine which script called it.

**Comment by P45H3** [comment]
?

**Comment by kunitoki** [comment]
can't you just use https://www.lua.org/manual/5.3/manual.html#lua_getinfo ? you only need to add lua_State* as last parameter of the binded function (or lambda), then use lua_getinfo to retrieve last call info

**Comment by dmitry-t** [comment]
Thank you @kunitoki

**Comment by P45H3** [comment]
I solved the problem like this:
```
std::string GetCalledFromLua( ) {
   lua_Debug debugInfo;
   for ( int level = 0; int b = lua_getstack( Source::m_pLuaEngine->lS( ), level, &debugInfo ); level++ ) {
	  lua_getinfo( Source::m_pLuaEngine->lS( ), "nSlf", &debugInfo );

	  if ( debugInfo.currentline != -1 ) {
		 //    printf( "GetCalledFromLua %s\n", debugInfo.short_src );
		 return std::string( debugInfo.short_src );
	  }
   }
   return debugInfo.short_src;
}
```
Just call in a function called from lua
