### ISSUE TITLE
New objects are not deleted

### ISSUE THREAD

**Issue by P45H3** [vinniefalco/LuaBridge#246]
There is a loop with conditional 600 iterations per tick
In it, I create an object of the class registered in lua
```
 .beginClass<Vector>( "Vector" ).addConstructor<void( * )( float, float, float )>( )
.addProperty( "x", &Vector::x )
 .addProperty( "y", &Vector::y )
.addProperty( "z", &Vector::z )
 .endClass( )
```
When the script starts, the process memory starts to eat up and over time it goes beyond 4gb and crashes

**Such a problem not only with the vector, but also with any other class returned to the script
If I return a normal type (for example int) then everything is fine**

If you call `collectgarbage` at the end of the function, then everything is fine

**Comment by P45H3** [comment]
N1 contribution

**Comment by dmitry-t** [comment]
Is Lua GC work this way? Could you please check? I mean if you create many array per second without the LuaBridge, is this reproducible?

**Comment by dmitry-t** [comment]
Also, if you are interested in LuaBridge, please participate. This is not a commercial product and nobody pays me or Vinnie.

**Comment by P45H3** [comment]
> Does Lua GC work this way? Could you please check? I mean if you create many array per second without the LuaBridge, is this reproducible?

Look. I tried with LUA version 5.4.3 (latest release) and with version (5.3.5). With version 5.4.3, memory filling is very fast (1g / per min). With 5.3, the memory is better cleaned, but there are micro freezes in everything. I dumped the used memory  (printf was called once every 60/200 sec) and got an approximate result like this
```
//5.4.3
60mb
63mb
65mb
etc.

//5.3
60mb
61mb
60mb
61mb
etc.
```
As you can see, with another version, the memory began to be cleared better, but this is not a normal operation
If I call a function that returns int (bool, char, etc), then the memory will not be eaten at all. The variable will simply disappear after exiting its life cycle (next iteration).

**Comment by dmitry-t** [comment]
Thank you!
But can you create let's say a table instead of a `Vector` userdata?
Such comparison would be more fair, because a Lua number is obviously faster than a table.
It would be even better if the tables have a `__gc` meta-method.

**Comment by P45H3** [comment]
They are removed when GC is called
I thought lua destroys objects right after going out of their scope like C ++

See another issue =)
