### ISSUE TITLE
Garbage Collector

### ISSUE THREAD

**Issue by P45H3** [vinniefalco/LuaBridge#250]
Good day. The garbage collector, when called, blocks the main thread for a sufficiently large amount of time, which is unacceptable in my program. How to set it up to run conditionally for 2ms each frame?

**Comment by dmitry-t** [comment]
Is this really a `LuaBridge` related question?

**Comment by kunitoki** [comment]
Lua method `collectgarbage` (and its c api counterpart) has several options that allows you to perform collections in steps instead of full cycles.

**Comment by P45H3** [comment]
It was solved by calling gc after each callback)
