### ISSUE TITLE
Restore reflection from Lua scripts

### ISSUE THREAD

**Issue by rpatters1** [vinniefalco/LuaBridge#267]
Before April 2019, it was possible for a Lua script to reflect the methods and properties of a class using string keys `__parent`, `__class`, `__propget`, and `__propset`. This was an incredibly useful tool for creating test scripts and development tools to maintain a large class framework exported into Lua.

I realize that they were removed for security reasons, but many users may place more priority on the ability to reflect classes from their scripts than on whether scripts can muck around in their object model. Especially in dev mode.

The [LuaBridge Reference Manual implies](http://vinniefalco.github.io/LuaBridge/Manual.html#s5) there is a way for a C program to expose the metatables, but I haven't been able to figure out how to do it. I am quite new to interfacing between C and Lua (or LuaBridge), so I'm not surprised that I am perplexed. If anyone could share an example of how to do this, I would appreciate it.

Meanwhile I would propose that some kind of optional reflection be reintroduced. It could be disabled either at compile time or run time. I've tried doing this myself, but I keep hitting roadblocks that go beyond both my knowledge and my risk tolerance level. The ideal solution would be safe from tinkering (unlike the previous method). But many users would probably be willing to risk the security, at least in debug mode, for the convenience of being able to use reflection scripts in Lua as a dev tool.

**Comment by dmitry-t** [comment]
There's possibility to turn off the security.
Though it was introduced long time ago.

**Comment by rpatters1** [comment]
I never could get it to work, but it doesn't really matter. I ended up creating my own tables to keep track of it and then exporting those into `LuaBridge`.
