### ISSUE TITLE
Bad userdata using Head. Lua 5.1 and 5.2 

### ISSUE THREAD

**Issue by aDevilInMe** [vinniefalco/LuaBridge#27]
The files which I am using are listed in this gist[1], it seems luabridge sees that an object is a userdata yet rejects it. This code used to work when luabridge was version 1 although it has since required a slight change of replacing "addMethod" with "addFunction" to mirror the change in head.

[1] https://gist.github.com/3811607/532e731ac6a2e0b124b1f8e0480bd5483a7676c7

**Comment by dmitry-t** [comment]
The issue is way too old. Is it solved? If so, how?

**Comment by dmitry-t** [comment]
Since there is no response for a long time, I consider the issue is somehow solved.
Feel free to reopen it or submit another issue.
