### ISSUE TITLE
compile error in c++20

### ISSUE THREAD

**Issue by tungfaifong** [vinniefalco/LuaBridge#278]
when I compile in c++20 , a compile error occur.

> LuaBridge/detail/Userdata.h:272:39: error: expected ‘)’ before ‘const’

should 
`UserdataValue<T> (UserdataValue<T> const&);`
be
`UserdataValue (UserdataValue<T> const&);`
?

fix it in #277

**Comment by dmitry-t** [comment]
Merged #277
