### ISSUE TITLE
Bool constructor does not require parameter

### ISSUE THREAD

**Issue by rpatters1** [vinniefalco/LuaBridge#283]
Suppose I have a c++ class with a constructor that accepts a `bool`:

```c++
class MyClass {
public:
   MyClass(bool switch) {}
};
```

Then suppose I add it to `LuaBridge` as follows:

```c++
   .beginClass<MyClass>("MyClass")
      .addConstructor(void (*) (bool))
      ...
```

Then the following Lua code *does not* generate a run time error:

```lua
local my_class = MyClass()
```

Instead, it passes `false` to the constructor, even if the default c++ parameter is `true`.

Is there any way to get Lua to report an error in this case? (And thus force the lua script to provide the parameter.) It seems like `bool` is the only parameter type for which this is an issue. If I change the constructor's parameter to `int`, Lua generates a runtime error as expected.

**Comment by dmitry-t** [comment]
Briefly, I'd expect such result.

It's a generic Lua rule: if you omit an argument, a `nil` is passed [instead](https://www.lua.org/manual/5.2/manual.html#3.4.10).
So
```Lua
function foo(a)
   print(a)
end
foo()
```
prints
```
nil
```

The LuaBridge in its turn uses the standard `lua_toboolean()` [function](https://www.lua.org/manual/5.2/manual.html#lua_toboolean) which returns true for any Lua value different from `false` and `nil`.
Implementation:
```C++
template<>
struct Stack<bool>
{
    ...
    static bool get(lua_State* L, int index) { return lua_toboolean(L, index) ? true : false; }
    ...
};
```

**Comment by rpatters1** [comment]
Yes, I agree that changing the bool conversion in LuaBridge is unwise.

I was thinking more along the lines of a special type that I could define in my code that "looks like" a bool in Lua to the extent that `true` and `false` work as initializers. Or even an override of `Stack<bool>` in my code. Or an option on `Stack<bool>` that for this instance only, `nil` doesn't convert to `false`.

So far I haven't thought of anything that works very well.

**Comment by rpatters1** [comment]
I decided to quit beating my head against this and change the constructor value to `int`. On balance, this seems like the safest way forward.
