### ISSUE TITLE
not support reference？but reference is widely used in cpp

### ISSUE THREAD

**Issue by yangyongzhen** [vinniefalco/LuaBridge#284]
I feel a little pity that luabriage is not support reference type in cpp,
but reference is widely used in cpp. how can i solve this problem?
for example:
//1:
int setEnableStatus(int axis, bool enable){
   return 0;
}
//2:
int getEnableStatus(int axis, bool& enable){
    enable = true;
    return 0;
}

luabridge::getGlobalNamespace(lua_state)
	.beginNamespace("test")
        .addFunction("setEnableStatus", setEnableStatus)
        .addFunction("getEnableStatus", getEnableStatus)
        .endNamespace();

see what you will get?
 cannot convert argument 1 from 'int' to
 'int &'
        with
        [
            Tail=luabridge::detail::TypeList<int &,luabridge::detail::MakeTypeList<>::Result>
        ]
![image](https://user-images.githubusercontent.com/8438899/167277923-83c3a2bb-e724-4120-b223-13914685aeff.png)

**Comment by yangyongzhen** [comment]
Is there any other way to solve the problem？
There are already a lot of references in my source code，need to rewrite them?

**Comment by dmitry-t** [comment]
There are no references in Lua.
If you need several return values in Lua, you simply return several values or return a table or return a userdata.
```lua
return 1, true
-- or
return {1, true}
-- or
return MyResult(1, true)
```
I guess the last alternative is the simplest one for use with LuaBridge.
You can also look for a closed issue about multiple return values for a solution for the first alternative.

**Comment by yangyongzhen** [comment]
> There are no references in Lua. If you need several return values in Lua, you simply return several values or return a table or return a userdata.
> 
> ```lua
> return 1, true
> -- or
> return {1, true}
> -- or
> return MyResult(1, true)
> ```
> 
> I guess the last alternative is the simplest one for use with LuaBridge. You can also look for a closed issue about multiple return values for a solution for the first alternative.

but this is not very good for use, also need to rewrite a lot of funcions, 
is there any other way? for example, can luabriage wraps Internal resolution ？

**Comment by yangyongzhen** [comment]
return MyResult(1, true)，doing like this? i just tryed, but new error occured.

struct RetResult0{
		int code;
		bool enable;
	};
...
RetResult0 getEnableStatus(int axis);

RetResult0 getEnableStatus(int axis){
		RetResult0 ret;
		ret.code = -1;
		ret.enable = false;
               return ret;
    }

 luabridge::getGlobalNamespace(L)
	.beginNamespace("driver")
	.beginClass<RetResult0>("RetResult0")
                    .addData("code", &RetResult0::code)
                    .addData("enable", &RetResult0::enable)
                .endClass() 
	.addFunction("getEnableStatus", LTDMC_Wrapper::getEnableStatus)
    .endNamespace();

![image](https://user-images.githubusercontent.com/8438899/167358018-90bccc09-f95e-4487-ac59-1cc93766e8c7.png)

**Comment by dmitry-t** [comment]
If looks like you are creating a RetResult0 instead from Lua, right?
In such case you also have to register a constructor for the class.

**Comment by yangyongzhen** [comment]
i am not sure  ,my whole  example is like this:
//main.cpp
#include <iostream>
#include "luareg.h"
int main(){
    std::cout << "hello test lua begin" << std::endl;
    lua_State* lua_state = luaL_newstate(); 
    luaL_openlibs(lua_state);
    luaRegister(lua_state);
    luaL_dofile(lua_state, "test.lua");
    lua_close(lua_state);
    std::cout << "hello test, lua end" << std::endl;
    return 0;
}

// luareg.h
#ifndef SERVICEPROJECT_LUAREG_H
#define SERVICEPROJECT_LUAREG_H

extern "C"
{
     #include "lua.h"
     #include "lauxlib.h"
     #include "lualib.h"
}
#include "LuaBridge\LuaBridge.h"
#include "ltdmcwrapper.h"

inline int luaRegister(lua_State* lua_state){
    luabridge::getGlobalNamespace(lua_state)
	.beginNamespace("driver")
	.beginClass<RetResult0>("RetResult0")
                    .addData("code", &RetResult0::code)
                    .addData("enable", &RetResult0::enable)
                .endClass() 
    .addFunction("init", LTDMC_Wrapper::init)
    .addFunction("setEnableStatus", LTDMC_Wrapper::setEnableStatus)
    .addFunction("getEnableStatus", &LTDMC_Wrapper::getEnableStatus)
    .endNamespace();
    return 0;
}
#endif

// ltdmcwrapper.cpp
#include <algorithm>
#include <iostream>

namespace LTDMC_Wrapper
{
	struct RetResult0{
		int code;
		bool enable;
	};
    
    int init(){
        std::cout << "init ENTER" << std::endl;
        return 0;
    }
    
    int setEnableStatus(int axis, bool enable){
	std::cout << "setEnableStatus ENTER" << std::endl;
        return 0;
    }

    RetResult0 getEnableStatus(int axis){
         std::cout << "getEnableStatus ENTER" << std::endl;
         RetResult0 ret;
         ret.code = -1;
         ret.enable = false;
         return ret;
    }
}

// test.lua
print("lua script ENTER") 
driver.init()
driver.setEnableStatus(0,1)
local ret = driver.getEnableStatus(1)
--print(ret)
print("lua script EXIT")

**Comment by yangyongzhen** [comment]
not support reference?why this is ok?
![image](https://user-images.githubusercontent.com/8438899/167526232-c1473693-a8ad-4a7a-ab15-0c3c8969866a.png)

**Comment by yangyongzhen** [comment]
> If looks like you are creating a RetResult0 instance from Lua, right? In such case you also have to register a constructor for the class.

thank you very much dmitry-t,this problem is solved,  my mistake is that, RetResult0 need with its namesplace , like this when registered
.beginClass<LTDMC_Wrapper::RetResult0>("RetResult0")
                    .addData("code", &LTDMC_Wrapper::RetResult0::code)
                    .addData("enable", &LTDMC_Wrapper::RetResult0::enable)
                .endClass()

**Comment by dmitry-t** [comment]
> not support reference?why this is ok?

I believe I answered above.
Lua just doesn't support references for numeric types.

Otherwise can you please provide _Lua code_ that uses numeric references?

**Comment by yangyongzhen** [comment]
thankyou!  i got it.  Lua doesn't support passing arguments by reference.  Unless somebody change the lua souce code

**Comment by yangyongzhen** [comment]
thankyou!  i got it.  Lua doesn't support passing arguments by reference.  Unless somebody change the lua souce code

**Comment by dmitry-t** [comment]
You're welcome!
Now closing the issue.
