### ISSUE TITLE
Throw an error from C++ with location returned in the error message

### ISSUE THREAD

**Issue by rpatters1** [vinniefalco/LuaBridge#293]
I have a c++ function like this:

```c++
void throw_error(const char* message)
{
   throw std::runtime_error(message);
}

int lua_callable_func()
{
   throw_error("This function is not currently supported.")
}
```

And a Lua script like this:

```lua
function my_function()
   lua_callable_func()
end

my_function()
```

The script aborts cleanly with the error message, as it should. But the message is missing the filename and line number in the Lua script where it happened. Is there any way to have that show in the error message as well?

**Comment by rpatters1** [comment]
Actually, it turns out that it has to be from a registered class. A straight function call into a namespace *does* report the file and line number. So the pared down scenario appears to be:

```c++
class RegisteredClass // this class is registered in LuaBridge
{
public:
   RegisteredClass() {} // this constructor is registered in LuaBridge
   unsupported_method() // this method is registered in LuaBridge
   { throw std::runtime_error("method not supported."); }
};
```

```lua
local instance = RegisteredClass()
instance:unsupported_method() // causes runtime error without file location info
```

The difference appears to be between line 379 and line 428 of `FuncTraits.h`. Line 379 reports file location info but line 428 does not.

**Comment by rpatters1** [comment]
Further info. For some reason, Namespace methods are called via `luaV_execute` but Class methods are called via `luaD_precall`.  This appears to be because of a difference in how `Namespace::addFunction` registers the function vs. how `CFunc::CallMemberFunctionHelper` registers the function.

**Comment by dmitry-t** [comment]
I need more time to understand what are trying to describe :)

To get stack info I basically use something like that:
```C++
int traceback(lua_State* L)
{
    lua_getglobal(L, "debug");
    if (!lua_istable(L, -1))
    {
        lua_pop(L, 1);
        return 1;
    }
    lua_getfield(L, -1, "traceback");
    if (!lua_isfunction(L, -1))
    {
        lua_pop(L, 2);
        return 1;
    }
    lua_pushvalue(L, 1); /* pass error message */
    lua_pushinteger(L, 2); /* skip this function and traceback */
    lua_call(L, 2, 1); /* call debug.traceback */
    return 1;
}
```
And register it in a state like that:
```C++
    lua_State* L = luaL_newstate();
    luaL_openlibs(L);
    lua_pushcfunction(L, &traceback);
```

**Comment by rpatters1** [comment]
I'm closing this and opening a new issue with a working test case to illustrate the problem.
