### ISSUE TITLE
Userdata::getClass() doesn't work with relative stack indices

### ISSUE THREAD

**Issue by vinniefalco** [vinniefalco/LuaBridge#31]
The error message code requires a positive index so it can label the arguments. Unfortunately this makes the getClass() function less flexible, as Stack<>::get() cannot be used with negative stack indexes when retrieving registered objects.

**Comment by dmitry-t** [comment]
Fixed in #184

**Comment by vinniefalco** [comment]
Wow, has it been 6 years already? How the time flies...
