### ISSUE TITLE
Version define not updated

### ISSUE THREAD

**Issue by PharosMarcusB** [vinniefalco/LuaBridge#321]
The version defines `LUABRIDGE_MINOR_VERSION` and `LUABRIDGE_VERSION` in [LuaBridge.h](https://github.com/vinniefalco/LuaBridge/blob/master/Source/LuaBridge/LuaBridge.h) didn't get updated before the master branch was tagged [2.8](https://github.com/vinniefalco/LuaBridge/releases/tag/2.8)

**Comment by dmitry-t** [comment]
Definitely it's not a good idea to change the tag now :(
I pushed the tag 2.9 since there were enough changes to step up the version.
