### ISSUE TITLE
LuaRef, access table keys

### ISSUE THREAD

**Issue by drunkenbird** [vinniefalco/LuaBridge#37]
Hey Vinnie, is there a means to iterate over a LuaRef and access keys and values?  Like pairs() or ipairs()?  I'd like to pass lua tables to juce to populate css-like data.

e.g.
in lua:

``` lua
cssstyle = {
  background = "ff336688",
  font_size = 11,
  font_name = "Arial"
}
```

in juce: (something to this effect)

``` c++
void doMap(LuaRef v) {

    HashMap<String, String>::Iterator it (v);

    while (it.next()) {
            String keyId = it.getKey();
            String val = it.getValue();
            //dostuff
    }

}
```

**Comment by dmitry-t** [comment]
I can't see anything that could be fixed, so closing the issue.
Please feel free to reopen the issue or create a new one.
