### ISSUE TITLE
size_t not working on Windows 64 bit, but works okay on Linux 64, Win 32

### ISSUE THREAD

**Issue by SnapperTT** [vinniefalco/LuaBridge#51]
Passing a function that returns or uses size_t as a type crashes luabridge in 64 bit windows, when cross compiling with mingw.

Example output (in wine):
DoTest
Assertion failed!

Program: Z:\home\twigger\turf\src\test\luatest\luatest64.exe
File: external/luabridge/detail/Userdata.h, Line 189

Expression: lua_istable (L, -1)

abnormal program termination

I have verified that this doesn't work on a win 7 box, but the cross compiled 32 bit target version does.

Below is my test setup, containing test code, makefiles and precompiled executables:
www.snapperthetwig.com/stuff/luatest.zip

**Comment by fwsGonzo** [comment]
Is this still broken? I'm having issues on Windows returning a simple 64-bit value

**Comment by dmitry-t** [comment]
Fixed: #63.
P.S. @fwsGonzo There was no pull request from you, or I have not find it. So I made the change that is identical to yours so simplify merge operations.

**Comment by dmitry-t** [comment]
Fixed: #63.
P.S. @fwsGonzo There was no pull request from you, or I have not find it. So I made the change that is identical to yours so simplify merge operations.
