### ISSUE TITLE
Proxy's rawset is not raw at all

### ISSUE THREAD

**Issue by nsf** [vinniefalco/LuaBridge#52]
Proxy's operator= does lua_rawset:
https://github.com/vinniefalco/LuaBridge/blob/master/Source/LuaBridge/detail/LuaRef.h#L179

While Proxy's rawset does lua_settable:
https://github.com/vinniefalco/LuaBridge/blob/master/Source/LuaBridge/detail/LuaRef.h#L196

I believe this is wrong and they should be swapped. Sorry for being lazy and not submitting a pull request.

**Comment by dmitry-t** [comment]
Closing the issue as irrelevant due to LuaRef refactoring.
