### ISSUE TITLE
LuaRef Help

### ISSUE THREAD

**Issue by fryedrycestyle** [vinniefalco/LuaBridge#61]
Hi,

First off, luabridge has been a great help to me in my project thus far.

But I need some help I'm afraid.

I'm trying to define a new table in my C++ header file as such:

```
luabridge::LuaRef press_start;
```

However I get a complaint of LuaRef not having a default constructor. 
Looking in the manual shows this syntax:
    LuaRef v (L);

However doing this in my header file:

```
luabridge::LuaRef press_start (L);
```

However that just gives me a complaint that variable L is not a type name.

So obviously I'm misunderstanding how to use LuaRef. I read the section in the manual and I still can't figure it out.

Help would be much appreciated.

Thanks!

**Comment by dmitry-t** [comment]
Answered.
