### ISSUE TITLE
LuaRef::Proxy behaves counter-intuitively

### ISSUE THREAD

**Issue by Bromeon** [vinniefalco/LuaBridge#70]
There are several situations where the table proxies do not behave as the user would expect.

One example is the nesting of index operators, which is a result of the short lifetime of the temporary LuaRef object created in Proxy::operator[].

``` cpp
LuaRef table = ...;
LuaRef entry = table["a"];
LuaRef subentry = entry["b"]; // fine

LuaRef direct = table["a"]["b"]; // panic (nil access) at runtime
```

Another one is the usage of standard streams:

``` cpp
LuaRef table = ...;
LuaRef entry = table["a"];

std::cout << entry; // fine
std::cout << table["a"]; // compile error: ambiguous operator<< (VS 2013)
```

This restricts the ability to write compact code with LuaBridge. When I use LuaRef instead of Proxy in those places (either by creating a temporary object in client code, or by replacing the return type of LuaRef::operator[]), the code behaves consistently as the user would expect.

This brings me to the question, what is the main purpose of the Proxy class in LuaBridge? Which features cannot be achieved using only LuaRef?

**Comment by dmitry-t** [comment]
Indeed the Proxy class mirroring LuaRef API seems to be strange.
