### ISSUE TITLE
Ambiguity compiler error with boost::bind() using XCode5 and Apple LLVM 5.0

### ISSUE THREAD

**Issue by werner291** [vinniefalco/LuaBridge#74]
Hello, I'm having compiler problems using this code:

void callLuaFunc(luabridge::LuaRef& function){
    function();
}

void LuaScriptManager::script_callAfterDelay(luabridge::LuaRef function, float delay){

```
boost::bind(hello,function);

//kernel.getScheduler().runAfterDelay(delay, callLuaFunc, function);
```

}

I get a compiler error when trying to compile this on the boost::bind line:
boost/bind/bind_cc.hpp:30:45: Ambiguous conversion for functional-style cast from 'luabridge::LuaRef' to 'list_type' (aka 'list1<B1>')

Is this something I'm doing wrong?

**Comment by dmitry-t** [comment]
If I understand correctly, the `hello` is some object, while the `function` must operate on a `hello` object? In such cases `boost::bind` expects an `object` member function as the second argument. And so the issue is not related to LuaBridge.
