### ISSUE TITLE
Exposing methods of std::vector

### ISSUE THREAD

**Issue by javdrher** [vinniefalco/LuaBridge#81]
Hi,

Currently, I am exposing some classes from a big project to Lua with LuaBridge, so far everything has gone absolutely great. One of the methods of a registered class returns a std::vector<double>, so I registered that as
beginClass< vector< double > >("VectorDouble")

Next, I tried to expose some of the std::vector methods for template parameter T=double for easy handling them in the Lua code:
.addFunction("size", &vector< double >::size)
.addFunction("empty", &vector< double >::empty)
.addFunction("get", &vector< double >::at)

The first two lines work, however, the last line (for data access) fails with the following message:
error: no instance of function template "luabridge::Namespace::Class< T >::addFunction [with T=std::vector< double, std::allocator< double >>]" matches the argument list
            argument types are: (const char [4], < unknown-type >)
            object type is: luabridge::Namespace::Class< std::vector< double, std::allocator< double >>>
                                .addFunction("get", &vector< double >::at)

I'm confused why some functions of std::vector can be registered, and some can not. I tried explicitly calling at on a dummy object of std::vector to make sure the method gets instantiated but this did not change anything.

Should I take another approach? Replacing std::vector with a custom class would require a lot of changes to the original project. Perhaps there is another way to access the data in the std::vector from the Lua code without registering methods? (writing the data to a table?)

**Comment by daavee** [comment]
This may be a little bit late, but for documentations sake:

The problem ist, that vector< T >::at has overloads and therefore the call to "addFunction" is ambitious.
You can solve this by explicitly specifying which overload you want to use.

F. e.:

.addFunction< vector< double >::reference ( vector< double >::* )( vector< double >::size_type ) >( "get", &vector< double >::at )
.addFunction< vector< double >::const_reference ( vector< double >::* )( vector< double >::size_type ) const >( "get", &vector< double >::at )
