### ISSUE TITLE
std::shared_ptr usage

### ISSUE THREAD

**Issue by iblues76** [vinniefalco/LuaBridge#88]
I have my engine which works with shared_ptr, every class has static create method which returns shared_ptr<T> of class instance, the instance is passed around the code as parameters too, how can i bind shared_ptr using LuaBridge?

**Comment by dmitry-t** [comment]
#231

**Comment by dmitry-t** [comment]
It's enough to register a concrete shared pointer instantiation in order to use it.

C++:
```C++
std::shared_ptr<MyClass> foo()
{
    return std::make_shared<MyClass>();
}

void bar(const std::shared_ptr<MyClass>& ptr)
{
    // Consume the ptr
}

luabridge::getGlobalNamespace(L)
    .beginClass<std::share_ptr<MyClass>>("MyClassPtr")
    .endClass()
    .addFunction("foo", &foo)
    .addFunction("bar", &bar);
```

Lua:
```Lua
bar(foo())
```

You can as many shared pointer instantiations as you need.
