### ISSUE TITLE
Problems with luahelpers.h and Stack.h

### ISSUE THREAD

**Issue by eliasdaler** [vinniefalco/LuaBridge#89]
I'm using Visual Studio 2013.
It seems like luahelpers.h cannot find all the nessesary headers if I don't include them myself in this file like this:

```
extern "C" {
# include "lua.h"
# include "lauxlib.h"
# include "lualib.h"
}
```

(Note, that I've added Lua's "include" folder to include directories)
After changing it, I need to change 460th line of Stack.h. from:

```
     lua_pushstring (L, str.c_str(), str.size());
```

to:

```
    lua_pushlstring (L, str.c_str(), str.size());
```

because there's another compile error which says 

> error C2660: 'luabridge::lua_pushstring' : function does not take 3 arguments. 

LuaBridge then works normally.

**Comment by IsemanTech** [comment]
Can confirm. That fix did the trick

**Comment by dmitry-t** [comment]
The change is on the master.
