### ISSUE TITLE
C++11 features

### ISSUE THREAD

**Issue by JoshuaBehrens** [vinniefalco/LuaBridge#90]
I just want to ask whether c++11 is featured in any way in any future of LuaBridge?
Like std::bind, std::shared/weak_ptr or even multithreading.

**Comment by dmitry-t** [comment]
#193, #231, #232

**Comment by dmitry-t** [comment]
Closing issue because it's too generic requirement from one hand and because some of the features have been implemented from the other hand.

**Comment by dmitry-t** [comment]
Closing issue because it's too generic requirement from one hand and because some of the features have been implemented from the other hand.

**Comment by dmitry-t** [comment]
#239
